// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type EntityCreateReq struct {
	SchemaName string       `json:"schemaName"`
	Fields     []FieldValue `json:"fields"`
}

type EntityCreateResp struct {
	Id string `json:"id"`
}

type EntityDeleteReq struct {
	SchemaName string `json:"schemaName"`
	Id         string `json:"id"`
}

type EntityDetailReq struct {
	SchemaName string `form:"schemaName"`
	Id         string `form:"id"`
}

type EntityDetailResp struct {
	Id         string       `json:"id"`
	SchemaName string       `json:"schemaName"`
	Fields     []FieldValue `json:"fields"`
	CreatedAt  string       `json:"createdAt"`
	UpdatedAt  string       `json:"updatedAt"`
}

type EntityListReq struct {
	SchemaName string `form:"schemaName"`
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"pageSize,default=20"`
}

type EntityListResp struct {
	Total int64              `json:"total"`
	List  []EntityDetailResp `json:"list"`
}

type EntityUpdateReq struct {
	SchemaName string       `json:"schemaName"`
	Id         string       `json:"id"`
	Fields     []FieldValue `json:"fields"`
}

type FieldDef struct {
	Name         string   `json:"name"`
	Type         string   `json:"type"` // string, int, float, bool, text, datetime, enum, json, array
	Required     bool     `json:"required"`
	MaxLength    int      `json:"maxLength,optional"`
	MinLength    int      `json:"minLength,optional"`
	DefaultValue string   `json:"defaultValue,optional"`
	EnumValues   []string `json:"enumValues,optional"`
	Description  string   `json:"description,optional"`
}

type FieldValue struct {
	Name  string `json:"name"`
	Type  string `json:"type"`  // 与 FieldDef.Type 对应
	Value string `json:"value"` // 值的字符串表示，后端根据 type 转换
}

type SchemaCreateReq struct {
	Name        string     `json:"name"`
	DisplayName string     `json:"displayName,optional"`
	Description string     `json:"description,optional"`
	Fields      []FieldDef `json:"fields"`
}

type SchemaDeleteReq struct {
	Name string `json:"name"`
}

type SchemaDetailReq struct {
	Name string `form:"name"`
}

type SchemaDetailResp struct {
	Name        string     `json:"name"`
	DisplayName string     `json:"displayName,optional"`
	Description string     `json:"description,optional"`
	Fields      []FieldDef `json:"fields"`
	CreatedAt   string     `json:"createdAt"`
	UpdatedAt   string     `json:"updatedAt"`
}

type SchemaListResp struct {
	Total int64              `json:"total"`
	List  []SchemaDetailResp `json:"list"`
}

type SchemaUpdateReq struct {
	Name        string     `json:"name"`
	DisplayName string     `json:"displayName,optional"`
	Description string     `json:"description,optional"`
	Fields      []FieldDef `json:"fields"`
}
