// Code generated by ent, DO NOT EDIT.

package schemadef

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the schemadef type in the database.
	Label = "schema_def"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeApp holds the string denoting the app edge name in mutations.
	EdgeApp = "app"
	// EdgeFieldDefs holds the string denoting the fielddefs edge name in mutations.
	EdgeFieldDefs = "fieldDefs"
	// EdgeEntityRecords holds the string denoting the entityrecords edge name in mutations.
	EdgeEntityRecords = "entityRecords"
	// Table holds the table name of the schemadef in the database.
	Table = "schema_defs"
	// AppTable is the table that holds the app relation/edge.
	AppTable = "schema_defs"
	// AppInverseTable is the table name for the App entity.
	// It exists in this package in order to avoid circular dependency with the "app" package.
	AppInverseTable = "apps"
	// AppColumn is the table column denoting the app relation/edge.
	AppColumn = "app_schema_defs"
	// FieldDefsTable is the table that holds the fieldDefs relation/edge.
	FieldDefsTable = "field_defs"
	// FieldDefsInverseTable is the table name for the FieldDef entity.
	// It exists in this package in order to avoid circular dependency with the "fielddef" package.
	FieldDefsInverseTable = "field_defs"
	// FieldDefsColumn is the table column denoting the fieldDefs relation/edge.
	FieldDefsColumn = "schema_def_field_defs"
	// EntityRecordsTable is the table that holds the entityRecords relation/edge.
	EntityRecordsTable = "entity_records"
	// EntityRecordsInverseTable is the table name for the EntityRecord entity.
	// It exists in this package in order to avoid circular dependency with the "entityrecord" package.
	EntityRecordsInverseTable = "entity_records"
	// EntityRecordsColumn is the table column denoting the entityRecords relation/edge.
	EntityRecordsColumn = "schema_def_entity_records"
)

// Columns holds all SQL columns for schemadef fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldName,
	FieldDescription,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "schema_defs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"app_schema_defs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the SchemaDef queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAppField orders the results by app field.
func ByAppField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAppStep(), sql.OrderByField(field, opts...))
	}
}

// ByFieldDefsCount orders the results by fieldDefs count.
func ByFieldDefsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFieldDefsStep(), opts...)
	}
}

// ByFieldDefs orders the results by fieldDefs terms.
func ByFieldDefs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFieldDefsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEntityRecordsCount orders the results by entityRecords count.
func ByEntityRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEntityRecordsStep(), opts...)
	}
}

// ByEntityRecords orders the results by entityRecords terms.
func ByEntityRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntityRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAppStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AppInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AppTable, AppColumn),
	)
}
func newFieldDefsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FieldDefsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FieldDefsTable, FieldDefsColumn),
	)
}
func newEntityRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntityRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EntityRecordsTable, EntityRecordsColumn),
	)
}
