// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"forma/internal/ent/migrate"

	"forma/internal/ent/fielddef"
	"forma/internal/ent/schemadef"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// FieldDef is the client for interacting with the FieldDef builders.
	FieldDef *FieldDefClient
	// SchemaDef is the client for interacting with the SchemaDef builders.
	SchemaDef *SchemaDefClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.FieldDef = NewFieldDefClient(c.config)
	c.SchemaDef = NewSchemaDefClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		FieldDef:  NewFieldDefClient(cfg),
		SchemaDef: NewSchemaDefClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		FieldDef:  NewFieldDefClient(cfg),
		SchemaDef: NewSchemaDefClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		FieldDef.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.FieldDef.Use(hooks...)
	c.SchemaDef.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.FieldDef.Intercept(interceptors...)
	c.SchemaDef.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *FieldDefMutation:
		return c.FieldDef.mutate(ctx, m)
	case *SchemaDefMutation:
		return c.SchemaDef.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// FieldDefClient is a client for the FieldDef schema.
type FieldDefClient struct {
	config
}

// NewFieldDefClient returns a client for the FieldDef from the given config.
func NewFieldDefClient(c config) *FieldDefClient {
	return &FieldDefClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `fielddef.Hooks(f(g(h())))`.
func (c *FieldDefClient) Use(hooks ...Hook) {
	c.hooks.FieldDef = append(c.hooks.FieldDef, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `fielddef.Intercept(f(g(h())))`.
func (c *FieldDefClient) Intercept(interceptors ...Interceptor) {
	c.inters.FieldDef = append(c.inters.FieldDef, interceptors...)
}

// Create returns a builder for creating a FieldDef entity.
func (c *FieldDefClient) Create() *FieldDefCreate {
	mutation := newFieldDefMutation(c.config, OpCreate)
	return &FieldDefCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FieldDef entities.
func (c *FieldDefClient) CreateBulk(builders ...*FieldDefCreate) *FieldDefCreateBulk {
	return &FieldDefCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FieldDefClient) MapCreateBulk(slice any, setFunc func(*FieldDefCreate, int)) *FieldDefCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FieldDefCreateBulk{err: fmt.Errorf("calling to FieldDefClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FieldDefCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FieldDefCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FieldDef.
func (c *FieldDefClient) Update() *FieldDefUpdate {
	mutation := newFieldDefMutation(c.config, OpUpdate)
	return &FieldDefUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FieldDefClient) UpdateOne(_m *FieldDef) *FieldDefUpdateOne {
	mutation := newFieldDefMutation(c.config, OpUpdateOne, withFieldDef(_m))
	return &FieldDefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FieldDefClient) UpdateOneID(id int) *FieldDefUpdateOne {
	mutation := newFieldDefMutation(c.config, OpUpdateOne, withFieldDefID(id))
	return &FieldDefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FieldDef.
func (c *FieldDefClient) Delete() *FieldDefDelete {
	mutation := newFieldDefMutation(c.config, OpDelete)
	return &FieldDefDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FieldDefClient) DeleteOne(_m *FieldDef) *FieldDefDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FieldDefClient) DeleteOneID(id int) *FieldDefDeleteOne {
	builder := c.Delete().Where(fielddef.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FieldDefDeleteOne{builder}
}

// Query returns a query builder for FieldDef.
func (c *FieldDefClient) Query() *FieldDefQuery {
	return &FieldDefQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFieldDef},
		inters: c.Interceptors(),
	}
}

// Get returns a FieldDef entity by its id.
func (c *FieldDefClient) Get(ctx context.Context, id int) (*FieldDef, error) {
	return c.Query().Where(fielddef.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FieldDefClient) GetX(ctx context.Context, id int) *FieldDef {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySchemaDef queries the schemaDef edge of a FieldDef.
func (c *FieldDefClient) QuerySchemaDef(_m *FieldDef) *SchemaDefQuery {
	query := (&SchemaDefClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(fielddef.Table, fielddef.FieldID, id),
			sqlgraph.To(schemadef.Table, schemadef.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, fielddef.SchemaDefTable, fielddef.SchemaDefColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FieldDefClient) Hooks() []Hook {
	return c.hooks.FieldDef
}

// Interceptors returns the client interceptors.
func (c *FieldDefClient) Interceptors() []Interceptor {
	return c.inters.FieldDef
}

func (c *FieldDefClient) mutate(ctx context.Context, m *FieldDefMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FieldDefCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FieldDefUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FieldDefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FieldDefDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FieldDef mutation op: %q", m.Op())
	}
}

// SchemaDefClient is a client for the SchemaDef schema.
type SchemaDefClient struct {
	config
}

// NewSchemaDefClient returns a client for the SchemaDef from the given config.
func NewSchemaDefClient(c config) *SchemaDefClient {
	return &SchemaDefClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `schemadef.Hooks(f(g(h())))`.
func (c *SchemaDefClient) Use(hooks ...Hook) {
	c.hooks.SchemaDef = append(c.hooks.SchemaDef, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `schemadef.Intercept(f(g(h())))`.
func (c *SchemaDefClient) Intercept(interceptors ...Interceptor) {
	c.inters.SchemaDef = append(c.inters.SchemaDef, interceptors...)
}

// Create returns a builder for creating a SchemaDef entity.
func (c *SchemaDefClient) Create() *SchemaDefCreate {
	mutation := newSchemaDefMutation(c.config, OpCreate)
	return &SchemaDefCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SchemaDef entities.
func (c *SchemaDefClient) CreateBulk(builders ...*SchemaDefCreate) *SchemaDefCreateBulk {
	return &SchemaDefCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SchemaDefClient) MapCreateBulk(slice any, setFunc func(*SchemaDefCreate, int)) *SchemaDefCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SchemaDefCreateBulk{err: fmt.Errorf("calling to SchemaDefClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SchemaDefCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SchemaDefCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SchemaDef.
func (c *SchemaDefClient) Update() *SchemaDefUpdate {
	mutation := newSchemaDefMutation(c.config, OpUpdate)
	return &SchemaDefUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SchemaDefClient) UpdateOne(_m *SchemaDef) *SchemaDefUpdateOne {
	mutation := newSchemaDefMutation(c.config, OpUpdateOne, withSchemaDef(_m))
	return &SchemaDefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SchemaDefClient) UpdateOneID(id int) *SchemaDefUpdateOne {
	mutation := newSchemaDefMutation(c.config, OpUpdateOne, withSchemaDefID(id))
	return &SchemaDefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SchemaDef.
func (c *SchemaDefClient) Delete() *SchemaDefDelete {
	mutation := newSchemaDefMutation(c.config, OpDelete)
	return &SchemaDefDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SchemaDefClient) DeleteOne(_m *SchemaDef) *SchemaDefDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SchemaDefClient) DeleteOneID(id int) *SchemaDefDeleteOne {
	builder := c.Delete().Where(schemadef.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SchemaDefDeleteOne{builder}
}

// Query returns a query builder for SchemaDef.
func (c *SchemaDefClient) Query() *SchemaDefQuery {
	return &SchemaDefQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSchemaDef},
		inters: c.Interceptors(),
	}
}

// Get returns a SchemaDef entity by its id.
func (c *SchemaDefClient) Get(ctx context.Context, id int) (*SchemaDef, error) {
	return c.Query().Where(schemadef.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SchemaDefClient) GetX(ctx context.Context, id int) *SchemaDef {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFieldDefs queries the fieldDefs edge of a SchemaDef.
func (c *SchemaDefClient) QueryFieldDefs(_m *SchemaDef) *FieldDefQuery {
	query := (&FieldDefClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(schemadef.Table, schemadef.FieldID, id),
			sqlgraph.To(fielddef.Table, fielddef.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, schemadef.FieldDefsTable, schemadef.FieldDefsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SchemaDefClient) Hooks() []Hook {
	return c.hooks.SchemaDef
}

// Interceptors returns the client interceptors.
func (c *SchemaDefClient) Interceptors() []Interceptor {
	return c.inters.SchemaDef
}

func (c *SchemaDefClient) mutate(ctx context.Context, m *SchemaDefMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SchemaDefCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SchemaDefUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SchemaDefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SchemaDefDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SchemaDef mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		FieldDef, SchemaDef []ent.Hook
	}
	inters struct {
		FieldDef, SchemaDef []ent.Interceptor
	}
)
