// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"forma/internal/ent/entityfieldvalue"
	"forma/internal/ent/entityrecord"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntityFieldValueCreate is the builder for creating a EntityFieldValue entity.
type EntityFieldValueCreate struct {
	config
	mutation *EntityFieldValueMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *EntityFieldValueCreate) SetName(v string) *EntityFieldValueCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *EntityFieldValueCreate) SetType(v entityfieldvalue.Type) *EntityFieldValueCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *EntityFieldValueCreate) SetValue(v string) *EntityFieldValueCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *EntityFieldValueCreate) SetNillableValue(v *string) *EntityFieldValueCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetEntityRecordID sets the "entityRecord" edge to the EntityRecord entity by ID.
func (_c *EntityFieldValueCreate) SetEntityRecordID(id int) *EntityFieldValueCreate {
	_c.mutation.SetEntityRecordID(id)
	return _c
}

// SetEntityRecord sets the "entityRecord" edge to the EntityRecord entity.
func (_c *EntityFieldValueCreate) SetEntityRecord(v *EntityRecord) *EntityFieldValueCreate {
	return _c.SetEntityRecordID(v.ID)
}

// Mutation returns the EntityFieldValueMutation object of the builder.
func (_c *EntityFieldValueCreate) Mutation() *EntityFieldValueMutation {
	return _c.mutation
}

// Save creates the EntityFieldValue in the database.
func (_c *EntityFieldValueCreate) Save(ctx context.Context) (*EntityFieldValue, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntityFieldValueCreate) SaveX(ctx context.Context) *EntityFieldValue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityFieldValueCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityFieldValueCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EntityFieldValueCreate) defaults() {
	if _, ok := _c.mutation.Value(); !ok {
		v := entityfieldvalue.DefaultValue
		_c.mutation.SetValue(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntityFieldValueCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "EntityFieldValue.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := entityfieldvalue.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EntityFieldValue.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "EntityFieldValue.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := entityfieldvalue.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "EntityFieldValue.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "EntityFieldValue.value"`)}
	}
	if len(_c.mutation.EntityRecordIDs()) == 0 {
		return &ValidationError{Name: "entityRecord", err: errors.New(`ent: missing required edge "EntityFieldValue.entityRecord"`)}
	}
	return nil
}

func (_c *EntityFieldValueCreate) sqlSave(ctx context.Context) (*EntityFieldValue, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntityFieldValueCreate) createSpec() (*EntityFieldValue, *sqlgraph.CreateSpec) {
	var (
		_node = &EntityFieldValue{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entityfieldvalue.Table, sqlgraph.NewFieldSpec(entityfieldvalue.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(entityfieldvalue.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(entityfieldvalue.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(entityfieldvalue.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if nodes := _c.mutation.EntityRecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityfieldvalue.EntityRecordTable,
			Columns: []string{entityfieldvalue.EntityRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entityrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.entity_record_field_values = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EntityFieldValue.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EntityFieldValueUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *EntityFieldValueCreate) OnConflict(opts ...sql.ConflictOption) *EntityFieldValueUpsertOne {
	_c.conflict = opts
	return &EntityFieldValueUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EntityFieldValue.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EntityFieldValueCreate) OnConflictColumns(columns ...string) *EntityFieldValueUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EntityFieldValueUpsertOne{
		create: _c,
	}
}

type (
	// EntityFieldValueUpsertOne is the builder for "upsert"-ing
	//  one EntityFieldValue node.
	EntityFieldValueUpsertOne struct {
		create *EntityFieldValueCreate
	}

	// EntityFieldValueUpsert is the "OnConflict" setter.
	EntityFieldValueUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *EntityFieldValueUpsert) SetName(v string) *EntityFieldValueUpsert {
	u.Set(entityfieldvalue.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EntityFieldValueUpsert) UpdateName() *EntityFieldValueUpsert {
	u.SetExcluded(entityfieldvalue.FieldName)
	return u
}

// SetType sets the "type" field.
func (u *EntityFieldValueUpsert) SetType(v entityfieldvalue.Type) *EntityFieldValueUpsert {
	u.Set(entityfieldvalue.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *EntityFieldValueUpsert) UpdateType() *EntityFieldValueUpsert {
	u.SetExcluded(entityfieldvalue.FieldType)
	return u
}

// SetValue sets the "value" field.
func (u *EntityFieldValueUpsert) SetValue(v string) *EntityFieldValueUpsert {
	u.Set(entityfieldvalue.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *EntityFieldValueUpsert) UpdateValue() *EntityFieldValueUpsert {
	u.SetExcluded(entityfieldvalue.FieldValue)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EntityFieldValue.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EntityFieldValueUpsertOne) UpdateNewValues() *EntityFieldValueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EntityFieldValue.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EntityFieldValueUpsertOne) Ignore() *EntityFieldValueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EntityFieldValueUpsertOne) DoNothing() *EntityFieldValueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EntityFieldValueCreate.OnConflict
// documentation for more info.
func (u *EntityFieldValueUpsertOne) Update(set func(*EntityFieldValueUpsert)) *EntityFieldValueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EntityFieldValueUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *EntityFieldValueUpsertOne) SetName(v string) *EntityFieldValueUpsertOne {
	return u.Update(func(s *EntityFieldValueUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EntityFieldValueUpsertOne) UpdateName() *EntityFieldValueUpsertOne {
	return u.Update(func(s *EntityFieldValueUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *EntityFieldValueUpsertOne) SetType(v entityfieldvalue.Type) *EntityFieldValueUpsertOne {
	return u.Update(func(s *EntityFieldValueUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *EntityFieldValueUpsertOne) UpdateType() *EntityFieldValueUpsertOne {
	return u.Update(func(s *EntityFieldValueUpsert) {
		s.UpdateType()
	})
}

// SetValue sets the "value" field.
func (u *EntityFieldValueUpsertOne) SetValue(v string) *EntityFieldValueUpsertOne {
	return u.Update(func(s *EntityFieldValueUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *EntityFieldValueUpsertOne) UpdateValue() *EntityFieldValueUpsertOne {
	return u.Update(func(s *EntityFieldValueUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *EntityFieldValueUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EntityFieldValueCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EntityFieldValueUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EntityFieldValueUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EntityFieldValueUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EntityFieldValueCreateBulk is the builder for creating many EntityFieldValue entities in bulk.
type EntityFieldValueCreateBulk struct {
	config
	err      error
	builders []*EntityFieldValueCreate
	conflict []sql.ConflictOption
}

// Save creates the EntityFieldValue entities in the database.
func (_c *EntityFieldValueCreateBulk) Save(ctx context.Context) ([]*EntityFieldValue, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EntityFieldValue, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntityFieldValueMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntityFieldValueCreateBulk) SaveX(ctx context.Context) []*EntityFieldValue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityFieldValueCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityFieldValueCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EntityFieldValue.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EntityFieldValueUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *EntityFieldValueCreateBulk) OnConflict(opts ...sql.ConflictOption) *EntityFieldValueUpsertBulk {
	_c.conflict = opts
	return &EntityFieldValueUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EntityFieldValue.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EntityFieldValueCreateBulk) OnConflictColumns(columns ...string) *EntityFieldValueUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EntityFieldValueUpsertBulk{
		create: _c,
	}
}

// EntityFieldValueUpsertBulk is the builder for "upsert"-ing
// a bulk of EntityFieldValue nodes.
type EntityFieldValueUpsertBulk struct {
	create *EntityFieldValueCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EntityFieldValue.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EntityFieldValueUpsertBulk) UpdateNewValues() *EntityFieldValueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EntityFieldValue.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EntityFieldValueUpsertBulk) Ignore() *EntityFieldValueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EntityFieldValueUpsertBulk) DoNothing() *EntityFieldValueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EntityFieldValueCreateBulk.OnConflict
// documentation for more info.
func (u *EntityFieldValueUpsertBulk) Update(set func(*EntityFieldValueUpsert)) *EntityFieldValueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EntityFieldValueUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *EntityFieldValueUpsertBulk) SetName(v string) *EntityFieldValueUpsertBulk {
	return u.Update(func(s *EntityFieldValueUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EntityFieldValueUpsertBulk) UpdateName() *EntityFieldValueUpsertBulk {
	return u.Update(func(s *EntityFieldValueUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *EntityFieldValueUpsertBulk) SetType(v entityfieldvalue.Type) *EntityFieldValueUpsertBulk {
	return u.Update(func(s *EntityFieldValueUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *EntityFieldValueUpsertBulk) UpdateType() *EntityFieldValueUpsertBulk {
	return u.Update(func(s *EntityFieldValueUpsert) {
		s.UpdateType()
	})
}

// SetValue sets the "value" field.
func (u *EntityFieldValueUpsertBulk) SetValue(v string) *EntityFieldValueUpsertBulk {
	return u.Update(func(s *EntityFieldValueUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *EntityFieldValueUpsertBulk) UpdateValue() *EntityFieldValueUpsertBulk {
	return u.Update(func(s *EntityFieldValueUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *EntityFieldValueUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EntityFieldValueCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EntityFieldValueCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EntityFieldValueUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
