// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"forma/internal/ent/entityrecord"
	"forma/internal/ent/schemadef"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// EntityRecord is the model entity for the EntityRecord schema.
type EntityRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntityRecordQuery when eager-loading is set.
	Edges                     EntityRecordEdges `json:"edges"`
	schema_def_entity_records *int
	selectValues              sql.SelectValues
}

// EntityRecordEdges holds the relations/edges for other nodes in the graph.
type EntityRecordEdges struct {
	// 所属Schema
	SchemaDef *SchemaDef `json:"schemaDef,omitempty"`
	// 实体的字段值
	FieldValues []*EntityFieldValue `json:"fieldValues,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SchemaDefOrErr returns the SchemaDef value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntityRecordEdges) SchemaDefOrErr() (*SchemaDef, error) {
	if e.SchemaDef != nil {
		return e.SchemaDef, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: schemadef.Label}
	}
	return nil, &NotLoadedError{edge: "schemaDef"}
}

// FieldValuesOrErr returns the FieldValues value or an error if the edge
// was not loaded in eager-loading.
func (e EntityRecordEdges) FieldValuesOrErr() ([]*EntityFieldValue, error) {
	if e.loadedTypes[1] {
		return e.FieldValues, nil
	}
	return nil, &NotLoadedError{edge: "fieldValues"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntityRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entityrecord.FieldID:
			values[i] = new(sql.NullInt64)
		case entityrecord.FieldCreateTime, entityrecord.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case entityrecord.ForeignKeys[0]: // schema_def_entity_records
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntityRecord fields.
func (_m *EntityRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entityrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case entityrecord.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case entityrecord.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case entityrecord.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field schema_def_entity_records", value)
			} else if value.Valid {
				_m.schema_def_entity_records = new(int)
				*_m.schema_def_entity_records = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EntityRecord.
// This includes values selected through modifiers, order, etc.
func (_m *EntityRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySchemaDef queries the "schemaDef" edge of the EntityRecord entity.
func (_m *EntityRecord) QuerySchemaDef() *SchemaDefQuery {
	return NewEntityRecordClient(_m.config).QuerySchemaDef(_m)
}

// QueryFieldValues queries the "fieldValues" edge of the EntityRecord entity.
func (_m *EntityRecord) QueryFieldValues() *EntityFieldValueQuery {
	return NewEntityRecordClient(_m.config).QueryFieldValues(_m)
}

// Update returns a builder for updating this EntityRecord.
// Note that you need to call EntityRecord.Unwrap() before calling this method if this EntityRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EntityRecord) Update() *EntityRecordUpdateOne {
	return NewEntityRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EntityRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EntityRecord) Unwrap() *EntityRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntityRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EntityRecord) String() string {
	var builder strings.Builder
	builder.WriteString("EntityRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EntityRecords is a parsable slice of EntityRecord.
type EntityRecords []*EntityRecord
