// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"forma/internal/ent/entityfieldvalue"
	"forma/internal/ent/entityrecord"
	"forma/internal/ent/fielddef"
	"forma/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntityFieldValueUpdate is the builder for updating EntityFieldValue entities.
type EntityFieldValueUpdate struct {
	config
	hooks    []Hook
	mutation *EntityFieldValueMutation
}

// Where appends a list predicates to the EntityFieldValueUpdate builder.
func (_u *EntityFieldValueUpdate) Where(ps ...predicate.EntityFieldValue) *EntityFieldValueUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *EntityFieldValueUpdate) SetUpdateTime(v time.Time) *EntityFieldValueUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetValue sets the "value" field.
func (_u *EntityFieldValueUpdate) SetValue(v string) *EntityFieldValueUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *EntityFieldValueUpdate) SetNillableValue(v *string) *EntityFieldValueUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetEntityRecordID sets the "entityRecord" edge to the EntityRecord entity by ID.
func (_u *EntityFieldValueUpdate) SetEntityRecordID(id int) *EntityFieldValueUpdate {
	_u.mutation.SetEntityRecordID(id)
	return _u
}

// SetEntityRecord sets the "entityRecord" edge to the EntityRecord entity.
func (_u *EntityFieldValueUpdate) SetEntityRecord(v *EntityRecord) *EntityFieldValueUpdate {
	return _u.SetEntityRecordID(v.ID)
}

// SetFieldDefID sets the "fieldDef" edge to the FieldDef entity by ID.
func (_u *EntityFieldValueUpdate) SetFieldDefID(id int) *EntityFieldValueUpdate {
	_u.mutation.SetFieldDefID(id)
	return _u
}

// SetFieldDef sets the "fieldDef" edge to the FieldDef entity.
func (_u *EntityFieldValueUpdate) SetFieldDef(v *FieldDef) *EntityFieldValueUpdate {
	return _u.SetFieldDefID(v.ID)
}

// Mutation returns the EntityFieldValueMutation object of the builder.
func (_u *EntityFieldValueUpdate) Mutation() *EntityFieldValueMutation {
	return _u.mutation
}

// ClearEntityRecord clears the "entityRecord" edge to the EntityRecord entity.
func (_u *EntityFieldValueUpdate) ClearEntityRecord() *EntityFieldValueUpdate {
	_u.mutation.ClearEntityRecord()
	return _u
}

// ClearFieldDef clears the "fieldDef" edge to the FieldDef entity.
func (_u *EntityFieldValueUpdate) ClearFieldDef() *EntityFieldValueUpdate {
	_u.mutation.ClearFieldDef()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntityFieldValueUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityFieldValueUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntityFieldValueUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityFieldValueUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntityFieldValueUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := entityfieldvalue.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityFieldValueUpdate) check() error {
	if _u.mutation.EntityRecordCleared() && len(_u.mutation.EntityRecordIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityFieldValue.entityRecord"`)
	}
	if _u.mutation.FieldDefCleared() && len(_u.mutation.FieldDefIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityFieldValue.fieldDef"`)
	}
	return nil
}

func (_u *EntityFieldValueUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entityfieldvalue.Table, entityfieldvalue.Columns, sqlgraph.NewFieldSpec(entityfieldvalue.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(entityfieldvalue.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(entityfieldvalue.FieldValue, field.TypeString, value)
	}
	if _u.mutation.EntityRecordCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityfieldvalue.EntityRecordTable,
			Columns: []string{entityfieldvalue.EntityRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entityrecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntityRecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityfieldvalue.EntityRecordTable,
			Columns: []string{entityfieldvalue.EntityRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entityrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FieldDefCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityfieldvalue.FieldDefTable,
			Columns: []string{entityfieldvalue.FieldDefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FieldDefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityfieldvalue.FieldDefTable,
			Columns: []string{entityfieldvalue.FieldDefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entityfieldvalue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntityFieldValueUpdateOne is the builder for updating a single EntityFieldValue entity.
type EntityFieldValueUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntityFieldValueMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *EntityFieldValueUpdateOne) SetUpdateTime(v time.Time) *EntityFieldValueUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetValue sets the "value" field.
func (_u *EntityFieldValueUpdateOne) SetValue(v string) *EntityFieldValueUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *EntityFieldValueUpdateOne) SetNillableValue(v *string) *EntityFieldValueUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetEntityRecordID sets the "entityRecord" edge to the EntityRecord entity by ID.
func (_u *EntityFieldValueUpdateOne) SetEntityRecordID(id int) *EntityFieldValueUpdateOne {
	_u.mutation.SetEntityRecordID(id)
	return _u
}

// SetEntityRecord sets the "entityRecord" edge to the EntityRecord entity.
func (_u *EntityFieldValueUpdateOne) SetEntityRecord(v *EntityRecord) *EntityFieldValueUpdateOne {
	return _u.SetEntityRecordID(v.ID)
}

// SetFieldDefID sets the "fieldDef" edge to the FieldDef entity by ID.
func (_u *EntityFieldValueUpdateOne) SetFieldDefID(id int) *EntityFieldValueUpdateOne {
	_u.mutation.SetFieldDefID(id)
	return _u
}

// SetFieldDef sets the "fieldDef" edge to the FieldDef entity.
func (_u *EntityFieldValueUpdateOne) SetFieldDef(v *FieldDef) *EntityFieldValueUpdateOne {
	return _u.SetFieldDefID(v.ID)
}

// Mutation returns the EntityFieldValueMutation object of the builder.
func (_u *EntityFieldValueUpdateOne) Mutation() *EntityFieldValueMutation {
	return _u.mutation
}

// ClearEntityRecord clears the "entityRecord" edge to the EntityRecord entity.
func (_u *EntityFieldValueUpdateOne) ClearEntityRecord() *EntityFieldValueUpdateOne {
	_u.mutation.ClearEntityRecord()
	return _u
}

// ClearFieldDef clears the "fieldDef" edge to the FieldDef entity.
func (_u *EntityFieldValueUpdateOne) ClearFieldDef() *EntityFieldValueUpdateOne {
	_u.mutation.ClearFieldDef()
	return _u
}

// Where appends a list predicates to the EntityFieldValueUpdate builder.
func (_u *EntityFieldValueUpdateOne) Where(ps ...predicate.EntityFieldValue) *EntityFieldValueUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntityFieldValueUpdateOne) Select(field string, fields ...string) *EntityFieldValueUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EntityFieldValue entity.
func (_u *EntityFieldValueUpdateOne) Save(ctx context.Context) (*EntityFieldValue, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityFieldValueUpdateOne) SaveX(ctx context.Context) *EntityFieldValue {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntityFieldValueUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityFieldValueUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntityFieldValueUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := entityfieldvalue.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityFieldValueUpdateOne) check() error {
	if _u.mutation.EntityRecordCleared() && len(_u.mutation.EntityRecordIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityFieldValue.entityRecord"`)
	}
	if _u.mutation.FieldDefCleared() && len(_u.mutation.FieldDefIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityFieldValue.fieldDef"`)
	}
	return nil
}

func (_u *EntityFieldValueUpdateOne) sqlSave(ctx context.Context) (_node *EntityFieldValue, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entityfieldvalue.Table, entityfieldvalue.Columns, sqlgraph.NewFieldSpec(entityfieldvalue.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EntityFieldValue.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entityfieldvalue.FieldID)
		for _, f := range fields {
			if !entityfieldvalue.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entityfieldvalue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(entityfieldvalue.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(entityfieldvalue.FieldValue, field.TypeString, value)
	}
	if _u.mutation.EntityRecordCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityfieldvalue.EntityRecordTable,
			Columns: []string{entityfieldvalue.EntityRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entityrecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntityRecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityfieldvalue.EntityRecordTable,
			Columns: []string{entityfieldvalue.EntityRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entityrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FieldDefCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityfieldvalue.FieldDefTable,
			Columns: []string{entityfieldvalue.FieldDefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FieldDefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityfieldvalue.FieldDefTable,
			Columns: []string{entityfieldvalue.FieldDefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EntityFieldValue{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entityfieldvalue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
