// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"forma/internal/ent/entityfieldvalue"
	"forma/internal/ent/entityrecord"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// EntityFieldValue is the model entity for the EntityFieldValue schema.
type EntityFieldValue struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 字段名
	Name string `json:"name,omitempty"`
	// 字段类型
	Type entityfieldvalue.Type `json:"type,omitempty"`
	// 字段值的字符串表示
	Value string `json:"value,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntityFieldValueQuery when eager-loading is set.
	Edges                      EntityFieldValueEdges `json:"edges"`
	entity_record_field_values *int
	selectValues               sql.SelectValues
}

// EntityFieldValueEdges holds the relations/edges for other nodes in the graph.
type EntityFieldValueEdges struct {
	// 所属实体记录
	EntityRecord *EntityRecord `json:"entityRecord,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EntityRecordOrErr returns the EntityRecord value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntityFieldValueEdges) EntityRecordOrErr() (*EntityRecord, error) {
	if e.EntityRecord != nil {
		return e.EntityRecord, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: entityrecord.Label}
	}
	return nil, &NotLoadedError{edge: "entityRecord"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntityFieldValue) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entityfieldvalue.FieldID:
			values[i] = new(sql.NullInt64)
		case entityfieldvalue.FieldName, entityfieldvalue.FieldType, entityfieldvalue.FieldValue:
			values[i] = new(sql.NullString)
		case entityfieldvalue.ForeignKeys[0]: // entity_record_field_values
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntityFieldValue fields.
func (_m *EntityFieldValue) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entityfieldvalue.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case entityfieldvalue.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case entityfieldvalue.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = entityfieldvalue.Type(value.String)
			}
		case entityfieldvalue.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case entityfieldvalue.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field entity_record_field_values", value)
			} else if value.Valid {
				_m.entity_record_field_values = new(int)
				*_m.entity_record_field_values = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the EntityFieldValue.
// This includes values selected through modifiers, order, etc.
func (_m *EntityFieldValue) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEntityRecord queries the "entityRecord" edge of the EntityFieldValue entity.
func (_m *EntityFieldValue) QueryEntityRecord() *EntityRecordQuery {
	return NewEntityFieldValueClient(_m.config).QueryEntityRecord(_m)
}

// Update returns a builder for updating this EntityFieldValue.
// Note that you need to call EntityFieldValue.Unwrap() before calling this method if this EntityFieldValue
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EntityFieldValue) Update() *EntityFieldValueUpdateOne {
	return NewEntityFieldValueClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EntityFieldValue entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EntityFieldValue) Unwrap() *EntityFieldValue {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntityFieldValue is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EntityFieldValue) String() string {
	var builder strings.Builder
	builder.WriteString("EntityFieldValue(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteByte(')')
	return builder.String()
}

// EntityFieldValues is a parsable slice of EntityFieldValue.
type EntityFieldValues []*EntityFieldValue
