// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"forma/internal/ent/entityfieldvalue"
	"forma/internal/ent/entityrecord"
	"forma/internal/ent/predicate"
	"forma/internal/ent/schemadef"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntityRecordUpdate is the builder for updating EntityRecord entities.
type EntityRecordUpdate struct {
	config
	hooks    []Hook
	mutation *EntityRecordMutation
}

// Where appends a list predicates to the EntityRecordUpdate builder.
func (_u *EntityRecordUpdate) Where(ps ...predicate.EntityRecord) *EntityRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *EntityRecordUpdate) SetUpdateTime(v time.Time) *EntityRecordUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetSchemaDefID sets the "schemaDef" edge to the SchemaDef entity by ID.
func (_u *EntityRecordUpdate) SetSchemaDefID(id int) *EntityRecordUpdate {
	_u.mutation.SetSchemaDefID(id)
	return _u
}

// SetSchemaDef sets the "schemaDef" edge to the SchemaDef entity.
func (_u *EntityRecordUpdate) SetSchemaDef(v *SchemaDef) *EntityRecordUpdate {
	return _u.SetSchemaDefID(v.ID)
}

// AddFieldValueIDs adds the "fieldValues" edge to the EntityFieldValue entity by IDs.
func (_u *EntityRecordUpdate) AddFieldValueIDs(ids ...int) *EntityRecordUpdate {
	_u.mutation.AddFieldValueIDs(ids...)
	return _u
}

// AddFieldValues adds the "fieldValues" edges to the EntityFieldValue entity.
func (_u *EntityRecordUpdate) AddFieldValues(v ...*EntityFieldValue) *EntityRecordUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFieldValueIDs(ids...)
}

// Mutation returns the EntityRecordMutation object of the builder.
func (_u *EntityRecordUpdate) Mutation() *EntityRecordMutation {
	return _u.mutation
}

// ClearSchemaDef clears the "schemaDef" edge to the SchemaDef entity.
func (_u *EntityRecordUpdate) ClearSchemaDef() *EntityRecordUpdate {
	_u.mutation.ClearSchemaDef()
	return _u
}

// ClearFieldValues clears all "fieldValues" edges to the EntityFieldValue entity.
func (_u *EntityRecordUpdate) ClearFieldValues() *EntityRecordUpdate {
	_u.mutation.ClearFieldValues()
	return _u
}

// RemoveFieldValueIDs removes the "fieldValues" edge to EntityFieldValue entities by IDs.
func (_u *EntityRecordUpdate) RemoveFieldValueIDs(ids ...int) *EntityRecordUpdate {
	_u.mutation.RemoveFieldValueIDs(ids...)
	return _u
}

// RemoveFieldValues removes "fieldValues" edges to EntityFieldValue entities.
func (_u *EntityRecordUpdate) RemoveFieldValues(v ...*EntityFieldValue) *EntityRecordUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFieldValueIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntityRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntityRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntityRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := entityrecord.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityRecordUpdate) check() error {
	if _u.mutation.SchemaDefCleared() && len(_u.mutation.SchemaDefIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityRecord.schemaDef"`)
	}
	return nil
}

func (_u *EntityRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entityrecord.Table, entityrecord.Columns, sqlgraph.NewFieldSpec(entityrecord.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(entityrecord.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.SchemaDefCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityrecord.SchemaDefTable,
			Columns: []string{entityrecord.SchemaDefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schemadef.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SchemaDefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityrecord.SchemaDefTable,
			Columns: []string{entityrecord.SchemaDefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schemadef.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FieldValuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entityrecord.FieldValuesTable,
			Columns: []string{entityrecord.FieldValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entityfieldvalue.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFieldValuesIDs(); len(nodes) > 0 && !_u.mutation.FieldValuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entityrecord.FieldValuesTable,
			Columns: []string{entityrecord.FieldValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entityfieldvalue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FieldValuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entityrecord.FieldValuesTable,
			Columns: []string{entityrecord.FieldValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entityfieldvalue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entityrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntityRecordUpdateOne is the builder for updating a single EntityRecord entity.
type EntityRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntityRecordMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *EntityRecordUpdateOne) SetUpdateTime(v time.Time) *EntityRecordUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetSchemaDefID sets the "schemaDef" edge to the SchemaDef entity by ID.
func (_u *EntityRecordUpdateOne) SetSchemaDefID(id int) *EntityRecordUpdateOne {
	_u.mutation.SetSchemaDefID(id)
	return _u
}

// SetSchemaDef sets the "schemaDef" edge to the SchemaDef entity.
func (_u *EntityRecordUpdateOne) SetSchemaDef(v *SchemaDef) *EntityRecordUpdateOne {
	return _u.SetSchemaDefID(v.ID)
}

// AddFieldValueIDs adds the "fieldValues" edge to the EntityFieldValue entity by IDs.
func (_u *EntityRecordUpdateOne) AddFieldValueIDs(ids ...int) *EntityRecordUpdateOne {
	_u.mutation.AddFieldValueIDs(ids...)
	return _u
}

// AddFieldValues adds the "fieldValues" edges to the EntityFieldValue entity.
func (_u *EntityRecordUpdateOne) AddFieldValues(v ...*EntityFieldValue) *EntityRecordUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFieldValueIDs(ids...)
}

// Mutation returns the EntityRecordMutation object of the builder.
func (_u *EntityRecordUpdateOne) Mutation() *EntityRecordMutation {
	return _u.mutation
}

// ClearSchemaDef clears the "schemaDef" edge to the SchemaDef entity.
func (_u *EntityRecordUpdateOne) ClearSchemaDef() *EntityRecordUpdateOne {
	_u.mutation.ClearSchemaDef()
	return _u
}

// ClearFieldValues clears all "fieldValues" edges to the EntityFieldValue entity.
func (_u *EntityRecordUpdateOne) ClearFieldValues() *EntityRecordUpdateOne {
	_u.mutation.ClearFieldValues()
	return _u
}

// RemoveFieldValueIDs removes the "fieldValues" edge to EntityFieldValue entities by IDs.
func (_u *EntityRecordUpdateOne) RemoveFieldValueIDs(ids ...int) *EntityRecordUpdateOne {
	_u.mutation.RemoveFieldValueIDs(ids...)
	return _u
}

// RemoveFieldValues removes "fieldValues" edges to EntityFieldValue entities.
func (_u *EntityRecordUpdateOne) RemoveFieldValues(v ...*EntityFieldValue) *EntityRecordUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFieldValueIDs(ids...)
}

// Where appends a list predicates to the EntityRecordUpdate builder.
func (_u *EntityRecordUpdateOne) Where(ps ...predicate.EntityRecord) *EntityRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntityRecordUpdateOne) Select(field string, fields ...string) *EntityRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EntityRecord entity.
func (_u *EntityRecordUpdateOne) Save(ctx context.Context) (*EntityRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityRecordUpdateOne) SaveX(ctx context.Context) *EntityRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntityRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntityRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := entityrecord.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityRecordUpdateOne) check() error {
	if _u.mutation.SchemaDefCleared() && len(_u.mutation.SchemaDefIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityRecord.schemaDef"`)
	}
	return nil
}

func (_u *EntityRecordUpdateOne) sqlSave(ctx context.Context) (_node *EntityRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entityrecord.Table, entityrecord.Columns, sqlgraph.NewFieldSpec(entityrecord.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EntityRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entityrecord.FieldID)
		for _, f := range fields {
			if !entityrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entityrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(entityrecord.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.SchemaDefCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityrecord.SchemaDefTable,
			Columns: []string{entityrecord.SchemaDefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schemadef.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SchemaDefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entityrecord.SchemaDefTable,
			Columns: []string{entityrecord.SchemaDefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schemadef.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FieldValuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entityrecord.FieldValuesTable,
			Columns: []string{entityrecord.FieldValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entityfieldvalue.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFieldValuesIDs(); len(nodes) > 0 && !_u.mutation.FieldValuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entityrecord.FieldValuesTable,
			Columns: []string{entityrecord.FieldValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entityfieldvalue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FieldValuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entityrecord.FieldValuesTable,
			Columns: []string{entityrecord.FieldValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entityfieldvalue.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EntityRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entityrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
