// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"forma/internal/ent/entityfieldvalue"
	"forma/internal/ent/entityrecord"
	"forma/internal/ent/fielddef"
	"forma/internal/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntityFieldValueQuery is the builder for querying EntityFieldValue entities.
type EntityFieldValueQuery struct {
	config
	ctx              *QueryContext
	order            []entityfieldvalue.OrderOption
	inters           []Interceptor
	predicates       []predicate.EntityFieldValue
	withEntityRecord *EntityRecordQuery
	withFieldDef     *FieldDefQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntityFieldValueQuery builder.
func (_q *EntityFieldValueQuery) Where(ps ...predicate.EntityFieldValue) *EntityFieldValueQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *EntityFieldValueQuery) Limit(limit int) *EntityFieldValueQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *EntityFieldValueQuery) Offset(offset int) *EntityFieldValueQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *EntityFieldValueQuery) Unique(unique bool) *EntityFieldValueQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *EntityFieldValueQuery) Order(o ...entityfieldvalue.OrderOption) *EntityFieldValueQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEntityRecord chains the current query on the "entityRecord" edge.
func (_q *EntityFieldValueQuery) QueryEntityRecord() *EntityRecordQuery {
	query := (&EntityRecordClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entityfieldvalue.Table, entityfieldvalue.FieldID, selector),
			sqlgraph.To(entityrecord.Table, entityrecord.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, entityfieldvalue.EntityRecordTable, entityfieldvalue.EntityRecordColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFieldDef chains the current query on the "fieldDef" edge.
func (_q *EntityFieldValueQuery) QueryFieldDef() *FieldDefQuery {
	query := (&FieldDefClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entityfieldvalue.Table, entityfieldvalue.FieldID, selector),
			sqlgraph.To(fielddef.Table, fielddef.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, entityfieldvalue.FieldDefTable, entityfieldvalue.FieldDefColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EntityFieldValue entity from the query.
// Returns a *NotFoundError when no EntityFieldValue was found.
func (_q *EntityFieldValueQuery) First(ctx context.Context) (*EntityFieldValue, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entityfieldvalue.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *EntityFieldValueQuery) FirstX(ctx context.Context) *EntityFieldValue {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntityFieldValue ID from the query.
// Returns a *NotFoundError when no EntityFieldValue ID was found.
func (_q *EntityFieldValueQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entityfieldvalue.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *EntityFieldValueQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntityFieldValue entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EntityFieldValue entity is found.
// Returns a *NotFoundError when no EntityFieldValue entities are found.
func (_q *EntityFieldValueQuery) Only(ctx context.Context) (*EntityFieldValue, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entityfieldvalue.Label}
	default:
		return nil, &NotSingularError{entityfieldvalue.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *EntityFieldValueQuery) OnlyX(ctx context.Context) *EntityFieldValue {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntityFieldValue ID in the query.
// Returns a *NotSingularError when more than one EntityFieldValue ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *EntityFieldValueQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entityfieldvalue.Label}
	default:
		err = &NotSingularError{entityfieldvalue.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *EntityFieldValueQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntityFieldValues.
func (_q *EntityFieldValueQuery) All(ctx context.Context) ([]*EntityFieldValue, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EntityFieldValue, *EntityFieldValueQuery]()
	return withInterceptors[[]*EntityFieldValue](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *EntityFieldValueQuery) AllX(ctx context.Context) []*EntityFieldValue {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntityFieldValue IDs.
func (_q *EntityFieldValueQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(entityfieldvalue.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *EntityFieldValueQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *EntityFieldValueQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*EntityFieldValueQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *EntityFieldValueQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *EntityFieldValueQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *EntityFieldValueQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntityFieldValueQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *EntityFieldValueQuery) Clone() *EntityFieldValueQuery {
	if _q == nil {
		return nil
	}
	return &EntityFieldValueQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]entityfieldvalue.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.EntityFieldValue{}, _q.predicates...),
		withEntityRecord: _q.withEntityRecord.Clone(),
		withFieldDef:     _q.withFieldDef.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEntityRecord tells the query-builder to eager-load the nodes that are connected to
// the "entityRecord" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EntityFieldValueQuery) WithEntityRecord(opts ...func(*EntityRecordQuery)) *EntityFieldValueQuery {
	query := (&EntityRecordClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEntityRecord = query
	return _q
}

// WithFieldDef tells the query-builder to eager-load the nodes that are connected to
// the "fieldDef" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EntityFieldValueQuery) WithFieldDef(opts ...func(*FieldDefQuery)) *EntityFieldValueQuery {
	query := (&FieldDefClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFieldDef = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Value string `json:"value,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntityFieldValue.Query().
//		GroupBy(entityfieldvalue.FieldValue).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *EntityFieldValueQuery) GroupBy(field string, fields ...string) *EntityFieldValueGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EntityFieldValueGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = entityfieldvalue.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Value string `json:"value,omitempty"`
//	}
//
//	client.EntityFieldValue.Query().
//		Select(entityfieldvalue.FieldValue).
//		Scan(ctx, &v)
func (_q *EntityFieldValueQuery) Select(fields ...string) *EntityFieldValueSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &EntityFieldValueSelect{EntityFieldValueQuery: _q}
	sbuild.label = entityfieldvalue.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EntityFieldValueSelect configured with the given aggregations.
func (_q *EntityFieldValueQuery) Aggregate(fns ...AggregateFunc) *EntityFieldValueSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *EntityFieldValueQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !entityfieldvalue.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *EntityFieldValueQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EntityFieldValue, error) {
	var (
		nodes       = []*EntityFieldValue{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withEntityRecord != nil,
			_q.withFieldDef != nil,
		}
	)
	if _q.withEntityRecord != nil || _q.withFieldDef != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, entityfieldvalue.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EntityFieldValue).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EntityFieldValue{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEntityRecord; query != nil {
		if err := _q.loadEntityRecord(ctx, query, nodes, nil,
			func(n *EntityFieldValue, e *EntityRecord) { n.Edges.EntityRecord = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFieldDef; query != nil {
		if err := _q.loadFieldDef(ctx, query, nodes, nil,
			func(n *EntityFieldValue, e *FieldDef) { n.Edges.FieldDef = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *EntityFieldValueQuery) loadEntityRecord(ctx context.Context, query *EntityRecordQuery, nodes []*EntityFieldValue, init func(*EntityFieldValue), assign func(*EntityFieldValue, *EntityRecord)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EntityFieldValue)
	for i := range nodes {
		if nodes[i].entity_record_field_values == nil {
			continue
		}
		fk := *nodes[i].entity_record_field_values
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(entityrecord.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "entity_record_field_values" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *EntityFieldValueQuery) loadFieldDef(ctx context.Context, query *FieldDefQuery, nodes []*EntityFieldValue, init func(*EntityFieldValue), assign func(*EntityFieldValue, *FieldDef)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EntityFieldValue)
	for i := range nodes {
		if nodes[i].field_def_field_values == nil {
			continue
		}
		fk := *nodes[i].field_def_field_values
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(fielddef.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "field_def_field_values" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *EntityFieldValueQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *EntityFieldValueQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(entityfieldvalue.Table, entityfieldvalue.Columns, sqlgraph.NewFieldSpec(entityfieldvalue.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entityfieldvalue.FieldID)
		for i := range fields {
			if fields[i] != entityfieldvalue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *EntityFieldValueQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(entityfieldvalue.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = entityfieldvalue.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntityFieldValueGroupBy is the group-by builder for EntityFieldValue entities.
type EntityFieldValueGroupBy struct {
	selector
	build *EntityFieldValueQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *EntityFieldValueGroupBy) Aggregate(fns ...AggregateFunc) *EntityFieldValueGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *EntityFieldValueGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntityFieldValueQuery, *EntityFieldValueGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *EntityFieldValueGroupBy) sqlScan(ctx context.Context, root *EntityFieldValueQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EntityFieldValueSelect is the builder for selecting fields of EntityFieldValue entities.
type EntityFieldValueSelect struct {
	*EntityFieldValueQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *EntityFieldValueSelect) Aggregate(fns ...AggregateFunc) *EntityFieldValueSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *EntityFieldValueSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntityFieldValueQuery, *EntityFieldValueSelect](ctx, _s.EntityFieldValueQuery, _s, _s.inters, v)
}

func (_s *EntityFieldValueSelect) sqlScan(ctx context.Context, root *EntityFieldValueQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
