// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"forma/internal/ent/entityfieldvalue"
	"forma/internal/ent/fielddef"
	"forma/internal/ent/predicate"
	"forma/internal/ent/schemadef"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FieldDefQuery is the builder for querying FieldDef entities.
type FieldDefQuery struct {
	config
	ctx             *QueryContext
	order           []fielddef.OrderOption
	inters          []Interceptor
	predicates      []predicate.FieldDef
	withSchemaDef   *SchemaDefQuery
	withFieldValues *EntityFieldValueQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FieldDefQuery builder.
func (_q *FieldDefQuery) Where(ps ...predicate.FieldDef) *FieldDefQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *FieldDefQuery) Limit(limit int) *FieldDefQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *FieldDefQuery) Offset(offset int) *FieldDefQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *FieldDefQuery) Unique(unique bool) *FieldDefQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *FieldDefQuery) Order(o ...fielddef.OrderOption) *FieldDefQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySchemaDef chains the current query on the "schemaDef" edge.
func (_q *FieldDefQuery) QuerySchemaDef() *SchemaDefQuery {
	query := (&SchemaDefClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fielddef.Table, fielddef.FieldID, selector),
			sqlgraph.To(schemadef.Table, schemadef.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, fielddef.SchemaDefTable, fielddef.SchemaDefColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFieldValues chains the current query on the "fieldValues" edge.
func (_q *FieldDefQuery) QueryFieldValues() *EntityFieldValueQuery {
	query := (&EntityFieldValueClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fielddef.Table, fielddef.FieldID, selector),
			sqlgraph.To(entityfieldvalue.Table, entityfieldvalue.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, fielddef.FieldValuesTable, fielddef.FieldValuesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FieldDef entity from the query.
// Returns a *NotFoundError when no FieldDef was found.
func (_q *FieldDefQuery) First(ctx context.Context) (*FieldDef, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fielddef.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *FieldDefQuery) FirstX(ctx context.Context) *FieldDef {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FieldDef ID from the query.
// Returns a *NotFoundError when no FieldDef ID was found.
func (_q *FieldDefQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fielddef.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *FieldDefQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FieldDef entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FieldDef entity is found.
// Returns a *NotFoundError when no FieldDef entities are found.
func (_q *FieldDefQuery) Only(ctx context.Context) (*FieldDef, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fielddef.Label}
	default:
		return nil, &NotSingularError{fielddef.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *FieldDefQuery) OnlyX(ctx context.Context) *FieldDef {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FieldDef ID in the query.
// Returns a *NotSingularError when more than one FieldDef ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *FieldDefQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fielddef.Label}
	default:
		err = &NotSingularError{fielddef.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *FieldDefQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FieldDefs.
func (_q *FieldDefQuery) All(ctx context.Context) ([]*FieldDef, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FieldDef, *FieldDefQuery]()
	return withInterceptors[[]*FieldDef](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *FieldDefQuery) AllX(ctx context.Context) []*FieldDef {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FieldDef IDs.
func (_q *FieldDefQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(fielddef.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *FieldDefQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *FieldDefQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*FieldDefQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *FieldDefQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *FieldDefQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *FieldDefQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FieldDefQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *FieldDefQuery) Clone() *FieldDefQuery {
	if _q == nil {
		return nil
	}
	return &FieldDefQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]fielddef.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.FieldDef{}, _q.predicates...),
		withSchemaDef:   _q.withSchemaDef.Clone(),
		withFieldValues: _q.withFieldValues.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSchemaDef tells the query-builder to eager-load the nodes that are connected to
// the "schemaDef" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FieldDefQuery) WithSchemaDef(opts ...func(*SchemaDefQuery)) *FieldDefQuery {
	query := (&SchemaDefClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSchemaDef = query
	return _q
}

// WithFieldValues tells the query-builder to eager-load the nodes that are connected to
// the "fieldValues" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FieldDefQuery) WithFieldValues(opts ...func(*EntityFieldValueQuery)) *FieldDefQuery {
	query := (&EntityFieldValueClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFieldValues = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FieldDef.Query().
//		GroupBy(fielddef.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *FieldDefQuery) GroupBy(field string, fields ...string) *FieldDefGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FieldDefGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = fielddef.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.FieldDef.Query().
//		Select(fielddef.FieldCreateTime).
//		Scan(ctx, &v)
func (_q *FieldDefQuery) Select(fields ...string) *FieldDefSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &FieldDefSelect{FieldDefQuery: _q}
	sbuild.label = fielddef.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FieldDefSelect configured with the given aggregations.
func (_q *FieldDefQuery) Aggregate(fns ...AggregateFunc) *FieldDefSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *FieldDefQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !fielddef.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *FieldDefQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FieldDef, error) {
	var (
		nodes       = []*FieldDef{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withSchemaDef != nil,
			_q.withFieldValues != nil,
		}
	)
	if _q.withSchemaDef != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, fielddef.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FieldDef).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FieldDef{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSchemaDef; query != nil {
		if err := _q.loadSchemaDef(ctx, query, nodes, nil,
			func(n *FieldDef, e *SchemaDef) { n.Edges.SchemaDef = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFieldValues; query != nil {
		if err := _q.loadFieldValues(ctx, query, nodes,
			func(n *FieldDef) { n.Edges.FieldValues = []*EntityFieldValue{} },
			func(n *FieldDef, e *EntityFieldValue) { n.Edges.FieldValues = append(n.Edges.FieldValues, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *FieldDefQuery) loadSchemaDef(ctx context.Context, query *SchemaDefQuery, nodes []*FieldDef, init func(*FieldDef), assign func(*FieldDef, *SchemaDef)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FieldDef)
	for i := range nodes {
		if nodes[i].schema_def_field_defs == nil {
			continue
		}
		fk := *nodes[i].schema_def_field_defs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(schemadef.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "schema_def_field_defs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *FieldDefQuery) loadFieldValues(ctx context.Context, query *EntityFieldValueQuery, nodes []*FieldDef, init func(*FieldDef), assign func(*FieldDef, *EntityFieldValue)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*FieldDef)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.EntityFieldValue(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(fielddef.FieldValuesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.field_def_field_values
		if fk == nil {
			return fmt.Errorf(`foreign-key "field_def_field_values" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "field_def_field_values" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *FieldDefQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *FieldDefQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(fielddef.Table, fielddef.Columns, sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fielddef.FieldID)
		for i := range fields {
			if fields[i] != fielddef.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *FieldDefQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(fielddef.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = fielddef.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FieldDefGroupBy is the group-by builder for FieldDef entities.
type FieldDefGroupBy struct {
	selector
	build *FieldDefQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *FieldDefGroupBy) Aggregate(fns ...AggregateFunc) *FieldDefGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *FieldDefGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FieldDefQuery, *FieldDefGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *FieldDefGroupBy) sqlScan(ctx context.Context, root *FieldDefQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FieldDefSelect is the builder for selecting fields of FieldDef entities.
type FieldDefSelect struct {
	*FieldDefQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *FieldDefSelect) Aggregate(fns ...AggregateFunc) *FieldDefSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *FieldDefSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FieldDefQuery, *FieldDefSelect](ctx, _s.FieldDefQuery, _s, _s.inters, v)
}

func (_s *FieldDefSelect) sqlScan(ctx context.Context, root *FieldDefQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
