// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"forma/internal/ent/fielddef"
	"forma/internal/ent/schemadef"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FieldDefCreate is the builder for creating a FieldDef entity.
type FieldDefCreate struct {
	config
	mutation *FieldDefMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *FieldDefCreate) SetCreateTime(v time.Time) *FieldDefCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *FieldDefCreate) SetNillableCreateTime(v *time.Time) *FieldDefCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *FieldDefCreate) SetUpdateTime(v time.Time) *FieldDefCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *FieldDefCreate) SetNillableUpdateTime(v *time.Time) *FieldDefCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *FieldDefCreate) SetName(v string) *FieldDefCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *FieldDefCreate) SetType(v fielddef.Type) *FieldDefCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetRequired sets the "required" field.
func (_c *FieldDefCreate) SetRequired(v bool) *FieldDefCreate {
	_c.mutation.SetRequired(v)
	return _c
}

// SetNillableRequired sets the "required" field if the given value is not nil.
func (_c *FieldDefCreate) SetNillableRequired(v *bool) *FieldDefCreate {
	if v != nil {
		_c.SetRequired(*v)
	}
	return _c
}

// SetMaxLength sets the "maxLength" field.
func (_c *FieldDefCreate) SetMaxLength(v int) *FieldDefCreate {
	_c.mutation.SetMaxLength(v)
	return _c
}

// SetNillableMaxLength sets the "maxLength" field if the given value is not nil.
func (_c *FieldDefCreate) SetNillableMaxLength(v *int) *FieldDefCreate {
	if v != nil {
		_c.SetMaxLength(*v)
	}
	return _c
}

// SetMinLength sets the "minLength" field.
func (_c *FieldDefCreate) SetMinLength(v int) *FieldDefCreate {
	_c.mutation.SetMinLength(v)
	return _c
}

// SetNillableMinLength sets the "minLength" field if the given value is not nil.
func (_c *FieldDefCreate) SetNillableMinLength(v *int) *FieldDefCreate {
	if v != nil {
		_c.SetMinLength(*v)
	}
	return _c
}

// SetEnumValues sets the "enumValues" field.
func (_c *FieldDefCreate) SetEnumValues(v []string) *FieldDefCreate {
	_c.mutation.SetEnumValues(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *FieldDefCreate) SetDescription(v string) *FieldDefCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *FieldDefCreate) SetNillableDescription(v *string) *FieldDefCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSchemaDefID sets the "schemaDef" edge to the SchemaDef entity by ID.
func (_c *FieldDefCreate) SetSchemaDefID(id int) *FieldDefCreate {
	_c.mutation.SetSchemaDefID(id)
	return _c
}

// SetNillableSchemaDefID sets the "schemaDef" edge to the SchemaDef entity by ID if the given value is not nil.
func (_c *FieldDefCreate) SetNillableSchemaDefID(id *int) *FieldDefCreate {
	if id != nil {
		_c = _c.SetSchemaDefID(*id)
	}
	return _c
}

// SetSchemaDef sets the "schemaDef" edge to the SchemaDef entity.
func (_c *FieldDefCreate) SetSchemaDef(v *SchemaDef) *FieldDefCreate {
	return _c.SetSchemaDefID(v.ID)
}

// Mutation returns the FieldDefMutation object of the builder.
func (_c *FieldDefCreate) Mutation() *FieldDefMutation {
	return _c.mutation
}

// Save creates the FieldDef in the database.
func (_c *FieldDefCreate) Save(ctx context.Context) (*FieldDef, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FieldDefCreate) SaveX(ctx context.Context) *FieldDef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FieldDefCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FieldDefCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FieldDefCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := fielddef.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := fielddef.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Required(); !ok {
		v := fielddef.DefaultRequired
		_c.mutation.SetRequired(v)
	}
	if _, ok := _c.mutation.MaxLength(); !ok {
		v := fielddef.DefaultMaxLength
		_c.mutation.SetMaxLength(v)
	}
	if _, ok := _c.mutation.MinLength(); !ok {
		v := fielddef.DefaultMinLength
		_c.mutation.SetMinLength(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FieldDefCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "FieldDef.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "FieldDef.update_time"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "FieldDef.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := fielddef.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FieldDef.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "FieldDef.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := fielddef.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "FieldDef.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Required(); !ok {
		return &ValidationError{Name: "required", err: errors.New(`ent: missing required field "FieldDef.required"`)}
	}
	if _, ok := _c.mutation.MaxLength(); !ok {
		return &ValidationError{Name: "maxLength", err: errors.New(`ent: missing required field "FieldDef.maxLength"`)}
	}
	if _, ok := _c.mutation.MinLength(); !ok {
		return &ValidationError{Name: "minLength", err: errors.New(`ent: missing required field "FieldDef.minLength"`)}
	}
	return nil
}

func (_c *FieldDefCreate) sqlSave(ctx context.Context) (*FieldDef, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FieldDefCreate) createSpec() (*FieldDef, *sqlgraph.CreateSpec) {
	var (
		_node = &FieldDef{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fielddef.Table, sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(fielddef.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(fielddef.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(fielddef.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(fielddef.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Required(); ok {
		_spec.SetField(fielddef.FieldRequired, field.TypeBool, value)
		_node.Required = value
	}
	if value, ok := _c.mutation.MaxLength(); ok {
		_spec.SetField(fielddef.FieldMaxLength, field.TypeInt, value)
		_node.MaxLength = value
	}
	if value, ok := _c.mutation.MinLength(); ok {
		_spec.SetField(fielddef.FieldMinLength, field.TypeInt, value)
		_node.MinLength = value
	}
	if value, ok := _c.mutation.EnumValues(); ok {
		_spec.SetField(fielddef.FieldEnumValues, field.TypeJSON, value)
		_node.EnumValues = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(fielddef.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.SchemaDefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fielddef.SchemaDefTable,
			Columns: []string{fielddef.SchemaDefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schemadef.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.schema_def_field_defs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FieldDef.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FieldDefUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *FieldDefCreate) OnConflict(opts ...sql.ConflictOption) *FieldDefUpsertOne {
	_c.conflict = opts
	return &FieldDefUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FieldDef.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FieldDefCreate) OnConflictColumns(columns ...string) *FieldDefUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FieldDefUpsertOne{
		create: _c,
	}
}

type (
	// FieldDefUpsertOne is the builder for "upsert"-ing
	//  one FieldDef node.
	FieldDefUpsertOne struct {
		create *FieldDefCreate
	}

	// FieldDefUpsert is the "OnConflict" setter.
	FieldDefUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *FieldDefUpsert) SetUpdateTime(v time.Time) *FieldDefUpsert {
	u.Set(fielddef.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *FieldDefUpsert) UpdateUpdateTime() *FieldDefUpsert {
	u.SetExcluded(fielddef.FieldUpdateTime)
	return u
}

// SetRequired sets the "required" field.
func (u *FieldDefUpsert) SetRequired(v bool) *FieldDefUpsert {
	u.Set(fielddef.FieldRequired, v)
	return u
}

// UpdateRequired sets the "required" field to the value that was provided on create.
func (u *FieldDefUpsert) UpdateRequired() *FieldDefUpsert {
	u.SetExcluded(fielddef.FieldRequired)
	return u
}

// SetMaxLength sets the "maxLength" field.
func (u *FieldDefUpsert) SetMaxLength(v int) *FieldDefUpsert {
	u.Set(fielddef.FieldMaxLength, v)
	return u
}

// UpdateMaxLength sets the "maxLength" field to the value that was provided on create.
func (u *FieldDefUpsert) UpdateMaxLength() *FieldDefUpsert {
	u.SetExcluded(fielddef.FieldMaxLength)
	return u
}

// AddMaxLength adds v to the "maxLength" field.
func (u *FieldDefUpsert) AddMaxLength(v int) *FieldDefUpsert {
	u.Add(fielddef.FieldMaxLength, v)
	return u
}

// SetMinLength sets the "minLength" field.
func (u *FieldDefUpsert) SetMinLength(v int) *FieldDefUpsert {
	u.Set(fielddef.FieldMinLength, v)
	return u
}

// UpdateMinLength sets the "minLength" field to the value that was provided on create.
func (u *FieldDefUpsert) UpdateMinLength() *FieldDefUpsert {
	u.SetExcluded(fielddef.FieldMinLength)
	return u
}

// AddMinLength adds v to the "minLength" field.
func (u *FieldDefUpsert) AddMinLength(v int) *FieldDefUpsert {
	u.Add(fielddef.FieldMinLength, v)
	return u
}

// SetEnumValues sets the "enumValues" field.
func (u *FieldDefUpsert) SetEnumValues(v []string) *FieldDefUpsert {
	u.Set(fielddef.FieldEnumValues, v)
	return u
}

// UpdateEnumValues sets the "enumValues" field to the value that was provided on create.
func (u *FieldDefUpsert) UpdateEnumValues() *FieldDefUpsert {
	u.SetExcluded(fielddef.FieldEnumValues)
	return u
}

// ClearEnumValues clears the value of the "enumValues" field.
func (u *FieldDefUpsert) ClearEnumValues() *FieldDefUpsert {
	u.SetNull(fielddef.FieldEnumValues)
	return u
}

// SetDescription sets the "description" field.
func (u *FieldDefUpsert) SetDescription(v string) *FieldDefUpsert {
	u.Set(fielddef.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FieldDefUpsert) UpdateDescription() *FieldDefUpsert {
	u.SetExcluded(fielddef.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *FieldDefUpsert) ClearDescription() *FieldDefUpsert {
	u.SetNull(fielddef.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FieldDef.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FieldDefUpsertOne) UpdateNewValues() *FieldDefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(fielddef.FieldCreateTime)
		}
		if _, exists := u.create.mutation.Name(); exists {
			s.SetIgnore(fielddef.FieldName)
		}
		if _, exists := u.create.mutation.GetType(); exists {
			s.SetIgnore(fielddef.FieldType)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FieldDef.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FieldDefUpsertOne) Ignore() *FieldDefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FieldDefUpsertOne) DoNothing() *FieldDefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FieldDefCreate.OnConflict
// documentation for more info.
func (u *FieldDefUpsertOne) Update(set func(*FieldDefUpsert)) *FieldDefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FieldDefUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *FieldDefUpsertOne) SetUpdateTime(v time.Time) *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *FieldDefUpsertOne) UpdateUpdateTime() *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetRequired sets the "required" field.
func (u *FieldDefUpsertOne) SetRequired(v bool) *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.SetRequired(v)
	})
}

// UpdateRequired sets the "required" field to the value that was provided on create.
func (u *FieldDefUpsertOne) UpdateRequired() *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.UpdateRequired()
	})
}

// SetMaxLength sets the "maxLength" field.
func (u *FieldDefUpsertOne) SetMaxLength(v int) *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.SetMaxLength(v)
	})
}

// AddMaxLength adds v to the "maxLength" field.
func (u *FieldDefUpsertOne) AddMaxLength(v int) *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.AddMaxLength(v)
	})
}

// UpdateMaxLength sets the "maxLength" field to the value that was provided on create.
func (u *FieldDefUpsertOne) UpdateMaxLength() *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.UpdateMaxLength()
	})
}

// SetMinLength sets the "minLength" field.
func (u *FieldDefUpsertOne) SetMinLength(v int) *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.SetMinLength(v)
	})
}

// AddMinLength adds v to the "minLength" field.
func (u *FieldDefUpsertOne) AddMinLength(v int) *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.AddMinLength(v)
	})
}

// UpdateMinLength sets the "minLength" field to the value that was provided on create.
func (u *FieldDefUpsertOne) UpdateMinLength() *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.UpdateMinLength()
	})
}

// SetEnumValues sets the "enumValues" field.
func (u *FieldDefUpsertOne) SetEnumValues(v []string) *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.SetEnumValues(v)
	})
}

// UpdateEnumValues sets the "enumValues" field to the value that was provided on create.
func (u *FieldDefUpsertOne) UpdateEnumValues() *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.UpdateEnumValues()
	})
}

// ClearEnumValues clears the value of the "enumValues" field.
func (u *FieldDefUpsertOne) ClearEnumValues() *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.ClearEnumValues()
	})
}

// SetDescription sets the "description" field.
func (u *FieldDefUpsertOne) SetDescription(v string) *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FieldDefUpsertOne) UpdateDescription() *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *FieldDefUpsertOne) ClearDescription() *FieldDefUpsertOne {
	return u.Update(func(s *FieldDefUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *FieldDefUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FieldDefCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FieldDefUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FieldDefUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FieldDefUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FieldDefCreateBulk is the builder for creating many FieldDef entities in bulk.
type FieldDefCreateBulk struct {
	config
	err      error
	builders []*FieldDefCreate
	conflict []sql.ConflictOption
}

// Save creates the FieldDef entities in the database.
func (_c *FieldDefCreateBulk) Save(ctx context.Context) ([]*FieldDef, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FieldDef, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FieldDefMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FieldDefCreateBulk) SaveX(ctx context.Context) []*FieldDef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FieldDefCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FieldDefCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FieldDef.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FieldDefUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *FieldDefCreateBulk) OnConflict(opts ...sql.ConflictOption) *FieldDefUpsertBulk {
	_c.conflict = opts
	return &FieldDefUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FieldDef.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FieldDefCreateBulk) OnConflictColumns(columns ...string) *FieldDefUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FieldDefUpsertBulk{
		create: _c,
	}
}

// FieldDefUpsertBulk is the builder for "upsert"-ing
// a bulk of FieldDef nodes.
type FieldDefUpsertBulk struct {
	create *FieldDefCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FieldDef.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FieldDefUpsertBulk) UpdateNewValues() *FieldDefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(fielddef.FieldCreateTime)
			}
			if _, exists := b.mutation.Name(); exists {
				s.SetIgnore(fielddef.FieldName)
			}
			if _, exists := b.mutation.GetType(); exists {
				s.SetIgnore(fielddef.FieldType)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FieldDef.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FieldDefUpsertBulk) Ignore() *FieldDefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FieldDefUpsertBulk) DoNothing() *FieldDefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FieldDefCreateBulk.OnConflict
// documentation for more info.
func (u *FieldDefUpsertBulk) Update(set func(*FieldDefUpsert)) *FieldDefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FieldDefUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *FieldDefUpsertBulk) SetUpdateTime(v time.Time) *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *FieldDefUpsertBulk) UpdateUpdateTime() *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetRequired sets the "required" field.
func (u *FieldDefUpsertBulk) SetRequired(v bool) *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.SetRequired(v)
	})
}

// UpdateRequired sets the "required" field to the value that was provided on create.
func (u *FieldDefUpsertBulk) UpdateRequired() *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.UpdateRequired()
	})
}

// SetMaxLength sets the "maxLength" field.
func (u *FieldDefUpsertBulk) SetMaxLength(v int) *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.SetMaxLength(v)
	})
}

// AddMaxLength adds v to the "maxLength" field.
func (u *FieldDefUpsertBulk) AddMaxLength(v int) *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.AddMaxLength(v)
	})
}

// UpdateMaxLength sets the "maxLength" field to the value that was provided on create.
func (u *FieldDefUpsertBulk) UpdateMaxLength() *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.UpdateMaxLength()
	})
}

// SetMinLength sets the "minLength" field.
func (u *FieldDefUpsertBulk) SetMinLength(v int) *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.SetMinLength(v)
	})
}

// AddMinLength adds v to the "minLength" field.
func (u *FieldDefUpsertBulk) AddMinLength(v int) *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.AddMinLength(v)
	})
}

// UpdateMinLength sets the "minLength" field to the value that was provided on create.
func (u *FieldDefUpsertBulk) UpdateMinLength() *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.UpdateMinLength()
	})
}

// SetEnumValues sets the "enumValues" field.
func (u *FieldDefUpsertBulk) SetEnumValues(v []string) *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.SetEnumValues(v)
	})
}

// UpdateEnumValues sets the "enumValues" field to the value that was provided on create.
func (u *FieldDefUpsertBulk) UpdateEnumValues() *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.UpdateEnumValues()
	})
}

// ClearEnumValues clears the value of the "enumValues" field.
func (u *FieldDefUpsertBulk) ClearEnumValues() *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.ClearEnumValues()
	})
}

// SetDescription sets the "description" field.
func (u *FieldDefUpsertBulk) SetDescription(v string) *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *FieldDefUpsertBulk) UpdateDescription() *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *FieldDefUpsertBulk) ClearDescription() *FieldDefUpsertBulk {
	return u.Update(func(s *FieldDefUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *FieldDefUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FieldDefCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FieldDefCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FieldDefUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
