// Code generated by ent, DO NOT EDIT.

package ent

import (
	"forma/internal/ent/app"
	"forma/internal/ent/entityfieldvalue"
	"forma/internal/ent/entityrecord"
	"forma/internal/ent/fielddef"
	"forma/internal/ent/schema"
	"forma/internal/ent/schemadef"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appMixin := schema.App{}.Mixin()
	appMixinFields0 := appMixin[0].Fields()
	_ = appMixinFields0
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescCreateTime is the schema descriptor for create_time field.
	appDescCreateTime := appMixinFields0[0].Descriptor()
	// app.DefaultCreateTime holds the default value on creation for the create_time field.
	app.DefaultCreateTime = appDescCreateTime.Default.(func() time.Time)
	// appDescUpdateTime is the schema descriptor for update_time field.
	appDescUpdateTime := appMixinFields0[1].Descriptor()
	// app.DefaultUpdateTime holds the default value on creation for the update_time field.
	app.DefaultUpdateTime = appDescUpdateTime.Default.(func() time.Time)
	// app.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	app.UpdateDefaultUpdateTime = appDescUpdateTime.UpdateDefault.(func() time.Time)
	// appDescCode is the schema descriptor for code field.
	appDescCode := appFields[0].Descriptor()
	// app.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	app.CodeValidator = appDescCode.Validators[0].(func(string) error)
	// appDescName is the schema descriptor for name field.
	appDescName := appFields[1].Descriptor()
	// app.NameValidator is a validator for the "name" field. It is called by the builders before save.
	app.NameValidator = appDescName.Validators[0].(func(string) error)
	entityfieldvalueMixin := schema.EntityFieldValue{}.Mixin()
	entityfieldvalueMixinFields0 := entityfieldvalueMixin[0].Fields()
	_ = entityfieldvalueMixinFields0
	entityfieldvalueFields := schema.EntityFieldValue{}.Fields()
	_ = entityfieldvalueFields
	// entityfieldvalueDescCreateTime is the schema descriptor for create_time field.
	entityfieldvalueDescCreateTime := entityfieldvalueMixinFields0[0].Descriptor()
	// entityfieldvalue.DefaultCreateTime holds the default value on creation for the create_time field.
	entityfieldvalue.DefaultCreateTime = entityfieldvalueDescCreateTime.Default.(func() time.Time)
	// entityfieldvalueDescUpdateTime is the schema descriptor for update_time field.
	entityfieldvalueDescUpdateTime := entityfieldvalueMixinFields0[1].Descriptor()
	// entityfieldvalue.DefaultUpdateTime holds the default value on creation for the update_time field.
	entityfieldvalue.DefaultUpdateTime = entityfieldvalueDescUpdateTime.Default.(func() time.Time)
	// entityfieldvalue.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	entityfieldvalue.UpdateDefaultUpdateTime = entityfieldvalueDescUpdateTime.UpdateDefault.(func() time.Time)
	// entityfieldvalueDescValue is the schema descriptor for value field.
	entityfieldvalueDescValue := entityfieldvalueFields[0].Descriptor()
	// entityfieldvalue.DefaultValue holds the default value on creation for the value field.
	entityfieldvalue.DefaultValue = entityfieldvalueDescValue.Default.(string)
	entityrecordMixin := schema.EntityRecord{}.Mixin()
	entityrecordMixinFields0 := entityrecordMixin[0].Fields()
	_ = entityrecordMixinFields0
	entityrecordFields := schema.EntityRecord{}.Fields()
	_ = entityrecordFields
	// entityrecordDescCreateTime is the schema descriptor for create_time field.
	entityrecordDescCreateTime := entityrecordMixinFields0[0].Descriptor()
	// entityrecord.DefaultCreateTime holds the default value on creation for the create_time field.
	entityrecord.DefaultCreateTime = entityrecordDescCreateTime.Default.(func() time.Time)
	// entityrecordDescUpdateTime is the schema descriptor for update_time field.
	entityrecordDescUpdateTime := entityrecordMixinFields0[1].Descriptor()
	// entityrecord.DefaultUpdateTime holds the default value on creation for the update_time field.
	entityrecord.DefaultUpdateTime = entityrecordDescUpdateTime.Default.(func() time.Time)
	// entityrecord.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	entityrecord.UpdateDefaultUpdateTime = entityrecordDescUpdateTime.UpdateDefault.(func() time.Time)
	fielddefMixin := schema.FieldDef{}.Mixin()
	fielddefMixinFields0 := fielddefMixin[0].Fields()
	_ = fielddefMixinFields0
	fielddefFields := schema.FieldDef{}.Fields()
	_ = fielddefFields
	// fielddefDescCreateTime is the schema descriptor for create_time field.
	fielddefDescCreateTime := fielddefMixinFields0[0].Descriptor()
	// fielddef.DefaultCreateTime holds the default value on creation for the create_time field.
	fielddef.DefaultCreateTime = fielddefDescCreateTime.Default.(func() time.Time)
	// fielddefDescUpdateTime is the schema descriptor for update_time field.
	fielddefDescUpdateTime := fielddefMixinFields0[1].Descriptor()
	// fielddef.DefaultUpdateTime holds the default value on creation for the update_time field.
	fielddef.DefaultUpdateTime = fielddefDescUpdateTime.Default.(func() time.Time)
	// fielddef.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	fielddef.UpdateDefaultUpdateTime = fielddefDescUpdateTime.UpdateDefault.(func() time.Time)
	// fielddefDescName is the schema descriptor for name field.
	fielddefDescName := fielddefFields[0].Descriptor()
	// fielddef.NameValidator is a validator for the "name" field. It is called by the builders before save.
	fielddef.NameValidator = fielddefDescName.Validators[0].(func(string) error)
	// fielddefDescRequired is the schema descriptor for required field.
	fielddefDescRequired := fielddefFields[2].Descriptor()
	// fielddef.DefaultRequired holds the default value on creation for the required field.
	fielddef.DefaultRequired = fielddefDescRequired.Default.(bool)
	// fielddefDescMaxLength is the schema descriptor for maxLength field.
	fielddefDescMaxLength := fielddefFields[3].Descriptor()
	// fielddef.DefaultMaxLength holds the default value on creation for the maxLength field.
	fielddef.DefaultMaxLength = fielddefDescMaxLength.Default.(int)
	// fielddefDescMinLength is the schema descriptor for minLength field.
	fielddefDescMinLength := fielddefFields[4].Descriptor()
	// fielddef.DefaultMinLength holds the default value on creation for the minLength field.
	fielddef.DefaultMinLength = fielddefDescMinLength.Default.(int)
	schemadefMixin := schema.SchemaDef{}.Mixin()
	schemadefMixinFields0 := schemadefMixin[0].Fields()
	_ = schemadefMixinFields0
	schemadefFields := schema.SchemaDef{}.Fields()
	_ = schemadefFields
	// schemadefDescCreateTime is the schema descriptor for create_time field.
	schemadefDescCreateTime := schemadefMixinFields0[0].Descriptor()
	// schemadef.DefaultCreateTime holds the default value on creation for the create_time field.
	schemadef.DefaultCreateTime = schemadefDescCreateTime.Default.(func() time.Time)
	// schemadefDescUpdateTime is the schema descriptor for update_time field.
	schemadefDescUpdateTime := schemadefMixinFields0[1].Descriptor()
	// schemadef.DefaultUpdateTime holds the default value on creation for the update_time field.
	schemadef.DefaultUpdateTime = schemadefDescUpdateTime.Default.(func() time.Time)
	// schemadef.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	schemadef.UpdateDefaultUpdateTime = schemadefDescUpdateTime.UpdateDefault.(func() time.Time)
	// schemadefDescName is the schema descriptor for name field.
	schemadefDescName := schemadefFields[0].Descriptor()
	// schemadef.NameValidator is a validator for the "name" field. It is called by the builders before save.
	schemadef.NameValidator = schemadefDescName.Validators[0].(func(string) error)
}
