// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"forma/internal/ent/entityrecord"
	"forma/internal/ent/fielddef"
	"forma/internal/ent/schemadef"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SchemaDefCreate is the builder for creating a SchemaDef entity.
type SchemaDefCreate struct {
	config
	mutation *SchemaDefMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *SchemaDefCreate) SetCreateTime(v time.Time) *SchemaDefCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SchemaDefCreate) SetNillableCreateTime(v *time.Time) *SchemaDefCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SchemaDefCreate) SetUpdateTime(v time.Time) *SchemaDefCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SchemaDefCreate) SetNillableUpdateTime(v *time.Time) *SchemaDefCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *SchemaDefCreate) SetName(v string) *SchemaDefCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SchemaDefCreate) SetDescription(v string) *SchemaDefCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SchemaDefCreate) SetNillableDescription(v *string) *SchemaDefCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// AddFieldDefIDs adds the "fieldDefs" edge to the FieldDef entity by IDs.
func (_c *SchemaDefCreate) AddFieldDefIDs(ids ...int) *SchemaDefCreate {
	_c.mutation.AddFieldDefIDs(ids...)
	return _c
}

// AddFieldDefs adds the "fieldDefs" edges to the FieldDef entity.
func (_c *SchemaDefCreate) AddFieldDefs(v ...*FieldDef) *SchemaDefCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFieldDefIDs(ids...)
}

// AddEntityRecordIDs adds the "entityRecords" edge to the EntityRecord entity by IDs.
func (_c *SchemaDefCreate) AddEntityRecordIDs(ids ...int) *SchemaDefCreate {
	_c.mutation.AddEntityRecordIDs(ids...)
	return _c
}

// AddEntityRecords adds the "entityRecords" edges to the EntityRecord entity.
func (_c *SchemaDefCreate) AddEntityRecords(v ...*EntityRecord) *SchemaDefCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEntityRecordIDs(ids...)
}

// Mutation returns the SchemaDefMutation object of the builder.
func (_c *SchemaDefCreate) Mutation() *SchemaDefMutation {
	return _c.mutation
}

// Save creates the SchemaDef in the database.
func (_c *SchemaDefCreate) Save(ctx context.Context) (*SchemaDef, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SchemaDefCreate) SaveX(ctx context.Context) *SchemaDef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchemaDefCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchemaDefCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SchemaDefCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := schemadef.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := schemadef.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SchemaDefCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "SchemaDef.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "SchemaDef.update_time"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SchemaDef.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := schemadef.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SchemaDef.name": %w`, err)}
		}
	}
	return nil
}

func (_c *SchemaDefCreate) sqlSave(ctx context.Context) (*SchemaDef, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SchemaDefCreate) createSpec() (*SchemaDef, *sqlgraph.CreateSpec) {
	var (
		_node = &SchemaDef{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(schemadef.Table, sqlgraph.NewFieldSpec(schemadef.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(schemadef.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(schemadef.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(schemadef.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(schemadef.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.FieldDefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schemadef.FieldDefsTable,
			Columns: []string{schemadef.FieldDefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EntityRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schemadef.EntityRecordsTable,
			Columns: []string{schemadef.EntityRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entityrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SchemaDef.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SchemaDefUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *SchemaDefCreate) OnConflict(opts ...sql.ConflictOption) *SchemaDefUpsertOne {
	_c.conflict = opts
	return &SchemaDefUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SchemaDef.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SchemaDefCreate) OnConflictColumns(columns ...string) *SchemaDefUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SchemaDefUpsertOne{
		create: _c,
	}
}

type (
	// SchemaDefUpsertOne is the builder for "upsert"-ing
	//  one SchemaDef node.
	SchemaDefUpsertOne struct {
		create *SchemaDefCreate
	}

	// SchemaDefUpsert is the "OnConflict" setter.
	SchemaDefUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *SchemaDefUpsert) SetUpdateTime(v time.Time) *SchemaDefUpsert {
	u.Set(schemadef.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SchemaDefUpsert) UpdateUpdateTime() *SchemaDefUpsert {
	u.SetExcluded(schemadef.FieldUpdateTime)
	return u
}

// SetDescription sets the "description" field.
func (u *SchemaDefUpsert) SetDescription(v string) *SchemaDefUpsert {
	u.Set(schemadef.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SchemaDefUpsert) UpdateDescription() *SchemaDefUpsert {
	u.SetExcluded(schemadef.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SchemaDefUpsert) ClearDescription() *SchemaDefUpsert {
	u.SetNull(schemadef.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SchemaDef.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SchemaDefUpsertOne) UpdateNewValues() *SchemaDefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(schemadef.FieldCreateTime)
		}
		if _, exists := u.create.mutation.Name(); exists {
			s.SetIgnore(schemadef.FieldName)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SchemaDef.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SchemaDefUpsertOne) Ignore() *SchemaDefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SchemaDefUpsertOne) DoNothing() *SchemaDefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SchemaDefCreate.OnConflict
// documentation for more info.
func (u *SchemaDefUpsertOne) Update(set func(*SchemaDefUpsert)) *SchemaDefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SchemaDefUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SchemaDefUpsertOne) SetUpdateTime(v time.Time) *SchemaDefUpsertOne {
	return u.Update(func(s *SchemaDefUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SchemaDefUpsertOne) UpdateUpdateTime() *SchemaDefUpsertOne {
	return u.Update(func(s *SchemaDefUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetDescription sets the "description" field.
func (u *SchemaDefUpsertOne) SetDescription(v string) *SchemaDefUpsertOne {
	return u.Update(func(s *SchemaDefUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SchemaDefUpsertOne) UpdateDescription() *SchemaDefUpsertOne {
	return u.Update(func(s *SchemaDefUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SchemaDefUpsertOne) ClearDescription() *SchemaDefUpsertOne {
	return u.Update(func(s *SchemaDefUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *SchemaDefUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SchemaDefCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SchemaDefUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SchemaDefUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SchemaDefUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SchemaDefCreateBulk is the builder for creating many SchemaDef entities in bulk.
type SchemaDefCreateBulk struct {
	config
	err      error
	builders []*SchemaDefCreate
	conflict []sql.ConflictOption
}

// Save creates the SchemaDef entities in the database.
func (_c *SchemaDefCreateBulk) Save(ctx context.Context) ([]*SchemaDef, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SchemaDef, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SchemaDefMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SchemaDefCreateBulk) SaveX(ctx context.Context) []*SchemaDef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchemaDefCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchemaDefCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SchemaDef.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SchemaDefUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *SchemaDefCreateBulk) OnConflict(opts ...sql.ConflictOption) *SchemaDefUpsertBulk {
	_c.conflict = opts
	return &SchemaDefUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SchemaDef.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SchemaDefCreateBulk) OnConflictColumns(columns ...string) *SchemaDefUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SchemaDefUpsertBulk{
		create: _c,
	}
}

// SchemaDefUpsertBulk is the builder for "upsert"-ing
// a bulk of SchemaDef nodes.
type SchemaDefUpsertBulk struct {
	create *SchemaDefCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SchemaDef.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SchemaDefUpsertBulk) UpdateNewValues() *SchemaDefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(schemadef.FieldCreateTime)
			}
			if _, exists := b.mutation.Name(); exists {
				s.SetIgnore(schemadef.FieldName)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SchemaDef.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SchemaDefUpsertBulk) Ignore() *SchemaDefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SchemaDefUpsertBulk) DoNothing() *SchemaDefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SchemaDefCreateBulk.OnConflict
// documentation for more info.
func (u *SchemaDefUpsertBulk) Update(set func(*SchemaDefUpsert)) *SchemaDefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SchemaDefUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SchemaDefUpsertBulk) SetUpdateTime(v time.Time) *SchemaDefUpsertBulk {
	return u.Update(func(s *SchemaDefUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SchemaDefUpsertBulk) UpdateUpdateTime() *SchemaDefUpsertBulk {
	return u.Update(func(s *SchemaDefUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetDescription sets the "description" field.
func (u *SchemaDefUpsertBulk) SetDescription(v string) *SchemaDefUpsertBulk {
	return u.Update(func(s *SchemaDefUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SchemaDefUpsertBulk) UpdateDescription() *SchemaDefUpsertBulk {
	return u.Update(func(s *SchemaDefUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SchemaDefUpsertBulk) ClearDescription() *SchemaDefUpsertBulk {
	return u.Update(func(s *SchemaDefUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *SchemaDefUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SchemaDefCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SchemaDefCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SchemaDefUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
