// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"forma/internal/ent/fielddef"
	"forma/internal/ent/predicate"
	"forma/internal/ent/schemadef"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SchemaDefUpdate is the builder for updating SchemaDef entities.
type SchemaDefUpdate struct {
	config
	hooks    []Hook
	mutation *SchemaDefMutation
}

// Where appends a list predicates to the SchemaDefUpdate builder.
func (_u *SchemaDefUpdate) Where(ps ...predicate.SchemaDef) *SchemaDefUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SchemaDefUpdate) SetUpdateTime(v time.Time) *SchemaDefUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *SchemaDefUpdate) SetDescription(v string) *SchemaDefUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SchemaDefUpdate) SetNillableDescription(v *string) *SchemaDefUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SchemaDefUpdate) ClearDescription() *SchemaDefUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// AddFieldDefIDs adds the "fieldDefs" edge to the FieldDef entity by IDs.
func (_u *SchemaDefUpdate) AddFieldDefIDs(ids ...int) *SchemaDefUpdate {
	_u.mutation.AddFieldDefIDs(ids...)
	return _u
}

// AddFieldDefs adds the "fieldDefs" edges to the FieldDef entity.
func (_u *SchemaDefUpdate) AddFieldDefs(v ...*FieldDef) *SchemaDefUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFieldDefIDs(ids...)
}

// Mutation returns the SchemaDefMutation object of the builder.
func (_u *SchemaDefUpdate) Mutation() *SchemaDefMutation {
	return _u.mutation
}

// ClearFieldDefs clears all "fieldDefs" edges to the FieldDef entity.
func (_u *SchemaDefUpdate) ClearFieldDefs() *SchemaDefUpdate {
	_u.mutation.ClearFieldDefs()
	return _u
}

// RemoveFieldDefIDs removes the "fieldDefs" edge to FieldDef entities by IDs.
func (_u *SchemaDefUpdate) RemoveFieldDefIDs(ids ...int) *SchemaDefUpdate {
	_u.mutation.RemoveFieldDefIDs(ids...)
	return _u
}

// RemoveFieldDefs removes "fieldDefs" edges to FieldDef entities.
func (_u *SchemaDefUpdate) RemoveFieldDefs(v ...*FieldDef) *SchemaDefUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFieldDefIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SchemaDefUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchemaDefUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SchemaDefUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchemaDefUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SchemaDefUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := schemadef.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *SchemaDefUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(schemadef.Table, schemadef.Columns, sqlgraph.NewFieldSpec(schemadef.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(schemadef.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(schemadef.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(schemadef.FieldDescription, field.TypeString)
	}
	if _u.mutation.FieldDefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schemadef.FieldDefsTable,
			Columns: []string{schemadef.FieldDefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFieldDefsIDs(); len(nodes) > 0 && !_u.mutation.FieldDefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schemadef.FieldDefsTable,
			Columns: []string{schemadef.FieldDefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FieldDefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schemadef.FieldDefsTable,
			Columns: []string{schemadef.FieldDefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schemadef.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SchemaDefUpdateOne is the builder for updating a single SchemaDef entity.
type SchemaDefUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SchemaDefMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *SchemaDefUpdateOne) SetUpdateTime(v time.Time) *SchemaDefUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *SchemaDefUpdateOne) SetDescription(v string) *SchemaDefUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SchemaDefUpdateOne) SetNillableDescription(v *string) *SchemaDefUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SchemaDefUpdateOne) ClearDescription() *SchemaDefUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// AddFieldDefIDs adds the "fieldDefs" edge to the FieldDef entity by IDs.
func (_u *SchemaDefUpdateOne) AddFieldDefIDs(ids ...int) *SchemaDefUpdateOne {
	_u.mutation.AddFieldDefIDs(ids...)
	return _u
}

// AddFieldDefs adds the "fieldDefs" edges to the FieldDef entity.
func (_u *SchemaDefUpdateOne) AddFieldDefs(v ...*FieldDef) *SchemaDefUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFieldDefIDs(ids...)
}

// Mutation returns the SchemaDefMutation object of the builder.
func (_u *SchemaDefUpdateOne) Mutation() *SchemaDefMutation {
	return _u.mutation
}

// ClearFieldDefs clears all "fieldDefs" edges to the FieldDef entity.
func (_u *SchemaDefUpdateOne) ClearFieldDefs() *SchemaDefUpdateOne {
	_u.mutation.ClearFieldDefs()
	return _u
}

// RemoveFieldDefIDs removes the "fieldDefs" edge to FieldDef entities by IDs.
func (_u *SchemaDefUpdateOne) RemoveFieldDefIDs(ids ...int) *SchemaDefUpdateOne {
	_u.mutation.RemoveFieldDefIDs(ids...)
	return _u
}

// RemoveFieldDefs removes "fieldDefs" edges to FieldDef entities.
func (_u *SchemaDefUpdateOne) RemoveFieldDefs(v ...*FieldDef) *SchemaDefUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFieldDefIDs(ids...)
}

// Where appends a list predicates to the SchemaDefUpdate builder.
func (_u *SchemaDefUpdateOne) Where(ps ...predicate.SchemaDef) *SchemaDefUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SchemaDefUpdateOne) Select(field string, fields ...string) *SchemaDefUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SchemaDef entity.
func (_u *SchemaDefUpdateOne) Save(ctx context.Context) (*SchemaDef, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchemaDefUpdateOne) SaveX(ctx context.Context) *SchemaDef {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SchemaDefUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchemaDefUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SchemaDefUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := schemadef.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *SchemaDefUpdateOne) sqlSave(ctx context.Context) (_node *SchemaDef, err error) {
	_spec := sqlgraph.NewUpdateSpec(schemadef.Table, schemadef.Columns, sqlgraph.NewFieldSpec(schemadef.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SchemaDef.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schemadef.FieldID)
		for _, f := range fields {
			if !schemadef.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schemadef.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(schemadef.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(schemadef.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(schemadef.FieldDescription, field.TypeString)
	}
	if _u.mutation.FieldDefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schemadef.FieldDefsTable,
			Columns: []string{schemadef.FieldDefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFieldDefsIDs(); len(nodes) > 0 && !_u.mutation.FieldDefsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schemadef.FieldDefsTable,
			Columns: []string{schemadef.FieldDefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FieldDefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   schemadef.FieldDefsTable,
			Columns: []string{schemadef.FieldDefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fielddef.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SchemaDef{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schemadef.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
