// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"forma/internal/ent/predicate"
	"forma/internal/ent/schemadef"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SchemaDefDelete is the builder for deleting a SchemaDef entity.
type SchemaDefDelete struct {
	config
	hooks    []Hook
	mutation *SchemaDefMutation
}

// Where appends a list predicates to the SchemaDefDelete builder.
func (_d *SchemaDefDelete) Where(ps ...predicate.SchemaDef) *SchemaDefDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SchemaDefDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SchemaDefDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SchemaDefDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(schemadef.Table, sqlgraph.NewFieldSpec(schemadef.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SchemaDefDeleteOne is the builder for deleting a single SchemaDef entity.
type SchemaDefDeleteOne struct {
	_d *SchemaDefDelete
}

// Where appends a list predicates to the SchemaDefDelete builder.
func (_d *SchemaDefDeleteOne) Where(ps ...predicate.SchemaDef) *SchemaDefDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SchemaDefDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{schemadef.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SchemaDefDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
