// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FieldDef is the predicate function for fielddef builders.
type FieldDef func(*sql.Selector)

// SchemaDef is the predicate function for schemadef builders.
type SchemaDef func(*sql.Selector)
