// Code generated by ent, DO NOT EDIT.

package entityfieldvalue

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the entityfieldvalue type in the database.
	Label = "entity_field_value"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// EdgeEntityRecord holds the string denoting the entityrecord edge name in mutations.
	EdgeEntityRecord = "entityRecord"
	// Table holds the table name of the entityfieldvalue in the database.
	Table = "entity_field_values"
	// EntityRecordTable is the table that holds the entityRecord relation/edge.
	EntityRecordTable = "entity_field_values"
	// EntityRecordInverseTable is the table name for the EntityRecord entity.
	// It exists in this package in order to avoid circular dependency with the "entityrecord" package.
	EntityRecordInverseTable = "entity_records"
	// EntityRecordColumn is the table column denoting the entityRecord relation/edge.
	EntityRecordColumn = "entity_record_field_values"
)

// Columns holds all SQL columns for entityfieldvalue fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldType,
	FieldValue,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "entity_field_values"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"entity_record_field_values",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultValue holds the default value on creation for the "value" field.
	DefaultValue string
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeString  Type = "string"
	TypeNumber  Type = "number"
	TypeBoolean Type = "boolean"
	TypeDate    Type = "date"
	TypeText    Type = "text"
	TypeEnum    Type = "enum"
	TypeJSON    Type = "json"
	TypeArray   Type = "array"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeString, TypeNumber, TypeBoolean, TypeDate, TypeText, TypeEnum, TypeJSON, TypeArray:
		return nil
	default:
		return fmt.Errorf("entityfieldvalue: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the EntityFieldValue queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByEntityRecordField orders the results by entityRecord field.
func ByEntityRecordField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntityRecordStep(), sql.OrderByField(field, opts...))
	}
}
func newEntityRecordStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntityRecordInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EntityRecordTable, EntityRecordColumn),
	)
}
