// Code generated by ent, DO NOT EDIT.

package entityfieldvalue

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the entityfieldvalue type in the database.
	Label = "entity_field_value"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// EdgeEntityRecord holds the string denoting the entityrecord edge name in mutations.
	EdgeEntityRecord = "entityRecord"
	// EdgeFieldDef holds the string denoting the fielddef edge name in mutations.
	EdgeFieldDef = "fieldDef"
	// Table holds the table name of the entityfieldvalue in the database.
	Table = "entity_field_values"
	// EntityRecordTable is the table that holds the entityRecord relation/edge.
	EntityRecordTable = "entity_field_values"
	// EntityRecordInverseTable is the table name for the EntityRecord entity.
	// It exists in this package in order to avoid circular dependency with the "entityrecord" package.
	EntityRecordInverseTable = "entity_records"
	// EntityRecordColumn is the table column denoting the entityRecord relation/edge.
	EntityRecordColumn = "entity_record_field_values"
	// FieldDefTable is the table that holds the fieldDef relation/edge.
	FieldDefTable = "entity_field_values"
	// FieldDefInverseTable is the table name for the FieldDef entity.
	// It exists in this package in order to avoid circular dependency with the "fielddef" package.
	FieldDefInverseTable = "field_defs"
	// FieldDefColumn is the table column denoting the fieldDef relation/edge.
	FieldDefColumn = "field_def_field_values"
)

// Columns holds all SQL columns for entityfieldvalue fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldValue,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "entity_field_values"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"entity_record_field_values",
	"field_def_field_values",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultValue holds the default value on creation for the "value" field.
	DefaultValue string
)

// OrderOption defines the ordering options for the EntityFieldValue queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByEntityRecordField orders the results by entityRecord field.
func ByEntityRecordField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntityRecordStep(), sql.OrderByField(field, opts...))
	}
}

// ByFieldDefField orders the results by fieldDef field.
func ByFieldDefField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFieldDefStep(), sql.OrderByField(field, opts...))
	}
}
func newEntityRecordStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntityRecordInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EntityRecordTable, EntityRecordColumn),
	)
}
func newFieldDefStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FieldDefInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FieldDefTable, FieldDefColumn),
	)
}
