// Code generated by ent, DO NOT EDIT.

package entityfieldvalue

import (
	"forma/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldLTE(FieldID, id))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldEQ(FieldValue, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.FieldContainsFold(FieldValue, v))
}

// HasEntityRecord applies the HasEdge predicate on the "entityRecord" edge.
func HasEntityRecord() predicate.EntityFieldValue {
	return predicate.EntityFieldValue(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EntityRecordTable, EntityRecordColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntityRecordWith applies the HasEdge predicate on the "entityRecord" edge with a given conditions (other predicates).
func HasEntityRecordWith(preds ...predicate.EntityRecord) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(func(s *sql.Selector) {
		step := newEntityRecordStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFieldDef applies the HasEdge predicate on the "fieldDef" edge.
func HasFieldDef() predicate.EntityFieldValue {
	return predicate.EntityFieldValue(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FieldDefTable, FieldDefColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFieldDefWith applies the HasEdge predicate on the "fieldDef" edge with a given conditions (other predicates).
func HasFieldDefWith(preds ...predicate.FieldDef) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(func(s *sql.Selector) {
		step := newFieldDefStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EntityFieldValue) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EntityFieldValue) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EntityFieldValue) predicate.EntityFieldValue {
	return predicate.EntityFieldValue(sql.NotPredicates(p))
}
