// Code generated by ent, DO NOT EDIT.

package fielddef

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the fielddef type in the database.
	Label = "field_def"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldRequired holds the string denoting the required field in the database.
	FieldRequired = "required"
	// FieldMaxLength holds the string denoting the maxlength field in the database.
	FieldMaxLength = "max_length"
	// FieldMinLength holds the string denoting the minlength field in the database.
	FieldMinLength = "min_length"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeSchemaDef holds the string denoting the schemadef edge name in mutations.
	EdgeSchemaDef = "schemaDef"
	// Table holds the table name of the fielddef in the database.
	Table = "field_defs"
	// SchemaDefTable is the table that holds the schemaDef relation/edge.
	SchemaDefTable = "field_defs"
	// SchemaDefInverseTable is the table name for the SchemaDef entity.
	// It exists in this package in order to avoid circular dependency with the "schemadef" package.
	SchemaDefInverseTable = "schema_defs"
	// SchemaDefColumn is the table column denoting the schemaDef relation/edge.
	SchemaDefColumn = "schema_def_field_defs"
)

// Columns holds all SQL columns for fielddef fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldName,
	FieldType,
	FieldRequired,
	FieldMaxLength,
	FieldMinLength,
	FieldDescription,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "field_defs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"schema_def_field_defs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultRequired holds the default value on creation for the "required" field.
	DefaultRequired bool
	// DefaultMaxLength holds the default value on creation for the "maxLength" field.
	DefaultMaxLength int
	// DefaultMinLength holds the default value on creation for the "minLength" field.
	DefaultMinLength int
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeString  Type = "string"
	TypeNumber  Type = "number"
	TypeBoolean Type = "boolean"
	TypeDate    Type = "date"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeString, TypeNumber, TypeBoolean, TypeDate:
		return nil
	default:
		return fmt.Errorf("fielddef: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the FieldDef queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByRequired orders the results by the required field.
func ByRequired(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequired, opts...).ToFunc()
}

// ByMaxLength orders the results by the maxLength field.
func ByMaxLength(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxLength, opts...).ToFunc()
}

// ByMinLength orders the results by the minLength field.
func ByMinLength(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinLength, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySchemaDefField orders the results by schemaDef field.
func BySchemaDefField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSchemaDefStep(), sql.OrderByField(field, opts...))
	}
}
func newSchemaDefStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SchemaDefInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SchemaDefTable, SchemaDefColumn),
	)
}
