// Code generated by ent, DO NOT EDIT.

package fielddef

import (
	"forma/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldUpdateTime, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldName, v))
}

// Required applies equality check predicate on the "required" field. It's identical to RequiredEQ.
func Required(v bool) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldRequired, v))
}

// MaxLength applies equality check predicate on the "maxLength" field. It's identical to MaxLengthEQ.
func MaxLength(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldMaxLength, v))
}

// MinLength applies equality check predicate on the "minLength" field. It's identical to MinLengthEQ.
func MinLength(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldMinLength, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldDescription, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLTE(FieldUpdateTime, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNotIn(FieldType, vs...))
}

// RequiredEQ applies the EQ predicate on the "required" field.
func RequiredEQ(v bool) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldRequired, v))
}

// RequiredNEQ applies the NEQ predicate on the "required" field.
func RequiredNEQ(v bool) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNEQ(FieldRequired, v))
}

// MaxLengthEQ applies the EQ predicate on the "maxLength" field.
func MaxLengthEQ(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldMaxLength, v))
}

// MaxLengthNEQ applies the NEQ predicate on the "maxLength" field.
func MaxLengthNEQ(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNEQ(FieldMaxLength, v))
}

// MaxLengthIn applies the In predicate on the "maxLength" field.
func MaxLengthIn(vs ...int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldIn(FieldMaxLength, vs...))
}

// MaxLengthNotIn applies the NotIn predicate on the "maxLength" field.
func MaxLengthNotIn(vs ...int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNotIn(FieldMaxLength, vs...))
}

// MaxLengthGT applies the GT predicate on the "maxLength" field.
func MaxLengthGT(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGT(FieldMaxLength, v))
}

// MaxLengthGTE applies the GTE predicate on the "maxLength" field.
func MaxLengthGTE(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGTE(FieldMaxLength, v))
}

// MaxLengthLT applies the LT predicate on the "maxLength" field.
func MaxLengthLT(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLT(FieldMaxLength, v))
}

// MaxLengthLTE applies the LTE predicate on the "maxLength" field.
func MaxLengthLTE(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLTE(FieldMaxLength, v))
}

// MinLengthEQ applies the EQ predicate on the "minLength" field.
func MinLengthEQ(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldMinLength, v))
}

// MinLengthNEQ applies the NEQ predicate on the "minLength" field.
func MinLengthNEQ(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNEQ(FieldMinLength, v))
}

// MinLengthIn applies the In predicate on the "minLength" field.
func MinLengthIn(vs ...int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldIn(FieldMinLength, vs...))
}

// MinLengthNotIn applies the NotIn predicate on the "minLength" field.
func MinLengthNotIn(vs ...int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNotIn(FieldMinLength, vs...))
}

// MinLengthGT applies the GT predicate on the "minLength" field.
func MinLengthGT(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGT(FieldMinLength, v))
}

// MinLengthGTE applies the GTE predicate on the "minLength" field.
func MinLengthGTE(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGTE(FieldMinLength, v))
}

// MinLengthLT applies the LT predicate on the "minLength" field.
func MinLengthLT(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLT(FieldMinLength, v))
}

// MinLengthLTE applies the LTE predicate on the "minLength" field.
func MinLengthLTE(v int) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLTE(FieldMinLength, v))
}

// EnumValuesIsNil applies the IsNil predicate on the "enumValues" field.
func EnumValuesIsNil() predicate.FieldDef {
	return predicate.FieldDef(sql.FieldIsNull(FieldEnumValues))
}

// EnumValuesNotNil applies the NotNil predicate on the "enumValues" field.
func EnumValuesNotNil() predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNotNull(FieldEnumValues))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.FieldDef {
	return predicate.FieldDef(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.FieldDef {
	return predicate.FieldDef(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.FieldDef {
	return predicate.FieldDef(sql.FieldContainsFold(FieldDescription, v))
}

// HasSchemaDef applies the HasEdge predicate on the "schemaDef" edge.
func HasSchemaDef() predicate.FieldDef {
	return predicate.FieldDef(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SchemaDefTable, SchemaDefColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSchemaDefWith applies the HasEdge predicate on the "schemaDef" edge with a given conditions (other predicates).
func HasSchemaDefWith(preds ...predicate.SchemaDef) predicate.FieldDef {
	return predicate.FieldDef(func(s *sql.Selector) {
		step := newSchemaDefStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFieldValues applies the HasEdge predicate on the "fieldValues" edge.
func HasFieldValues() predicate.FieldDef {
	return predicate.FieldDef(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FieldValuesTable, FieldValuesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFieldValuesWith applies the HasEdge predicate on the "fieldValues" edge with a given conditions (other predicates).
func HasFieldValuesWith(preds ...predicate.EntityFieldValue) predicate.FieldDef {
	return predicate.FieldDef(func(s *sql.Selector) {
		step := newFieldValuesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FieldDef) predicate.FieldDef {
	return predicate.FieldDef(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FieldDef) predicate.FieldDef {
	return predicate.FieldDef(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FieldDef) predicate.FieldDef {
	return predicate.FieldDef(sql.NotPredicates(p))
}
